# states_data.py
# Data for all 28 states in India, with at least 10 food items per state, including ingredients, calories, and nutritional details

STATE_FOODS = {
    "Andhra Pradesh": [
        ("Pesarattu", "Green Gram, Rice, Green Chillies, Ginger", 200, 8, 30, 5, "Breakfast"),
        ("Gongura Pachadi", "Sorrel Leaves, Red Chillies, Garlic, Tamarind", 150, 2, 10, 10, "Side"),
        ("Prawn Iguru", "Prawns, Onions, Tomatoes, Spices", 250, 20, 5, 15, "Dinner"),
        ("Biryani", "Rice, Chicken, Spices, Saffron", 600, 25, 80, 20, "Lunch"),
        ("Pulihora", "Rice, Tamarind, Peanuts, Spices", 300, 5, 50, 10, "Lunch"),
        ("Gutti Vankaya", "Brinjal, Peanuts, Spices, Coconut", 200, 4, 15, 12, "Side"),
        ("Chepala Pulusu", "Fish, Tamarind, Onions, Spices", 300, 22, 10, 18, "Dinner"),
        ("Ariselu", "Rice Flour, Jaggery, Ghee", 400, 3, 60, 15, "Snack"),
        ("Pappu Charu", "Lentils, Tamarind, Tomatoes, Spices", 150, 6, 20, 3, "Side"),
        ("Kodi Kura", "Chicken, Onions, Tomatoes, Spices", 350, 28, 10, 20, "Dinner"),
        ("Royyala Vepudu", "Prawns, Garlic, Curry Leaves, Red Chillies", 280, 22, 8, 16, "Dinner"),
        ("Bendakaya Pulusu", "Okra, Tamarind, Jaggery, Spices", 180, 3, 25, 6, "Side"),
        ("Miriyala Rasam", "Black Pepper, Tamarind, Garlic, Cumin", 120, 2, 15, 4, "Side"),
        ("Kobbari Annam", "Rice, Coconut, Cashews, Spices", 320, 6, 50, 10, "Lunch"),
        ("Chintakaya Pachadi", "Raw Tamarind, Green Chillies, Spices", 140, 2, 12, 8, "Side"),
        ("Natukodi Pulusu", "Country Chicken, Tamarind, Spices", 380, 30, 12, 22, "Dinner"),
        ("Ulava Charu", "Horse Gram, Garlic, Spices", 160, 7, 22, 3, "Side"),
        ("Ragi Sangati", "Finger Millet, Rice, Water", 220, 5, 40, 2, "Lunch"),
        ("Kakarakaya Fry", "Bitter Gourd, Spices, Oil", 170, 3, 20, 8, "Side"),
        ("Pootharekulu", "Rice Flour, Sugar, Ghee", 350, 4, 55, 12, "Snack"),
        ("Mukkala Pulusu", "Mixed Vegetables, Tamarind, Spices", 190, 4, 28, 6, "Side"),
        ("Pappula Podi", "Roasted Gram, Red Chillies, Spices", 130, 5, 15, 5, "Side"),
        ("Chicken Vepudu", "Chicken, Green Chillies, Curry Leaves", 360, 27, 8, 23, "Dinner"),
        ("Bobbatlu", "Wheat Flour, Lentils, Jaggery", 380, 8, 60, 12, "Snack"),
        ("Dondakaya Fry", "Ivy Gourd, Spices, Peanuts", 160, 3, 18, 7, "Side"),
        ("Sunnundalu", "Urad Dal, Jaggery, Ghee", 420, 10, 60, 15, "Snack"),
        ("Tomato Pappu", "Lentils, Tomatoes, Green Chillies", 170, 7, 23, 4, "Side"),
        ("Pallikaram Dosa", "Rice, Peanuts, Spices", 240, 6, 35, 8, "Breakfast"),
        ("Mutton Iguru", "Mutton, Onions, Spices", 430, 32, 10, 28, "Dinner"),
        ("Kandi Podi", "Toor Dal, Red Chillies, Garlic", 140, 6, 18, 4, "Side")
    ],
    "Arunachal Pradesh": [
        ("Pika Pila", "Rice, Bamboo Shoot, Spices, Ginger", 200, 4, 35, 5, "Lunch"),
        ("Lukter", "Beef, Bamboo Shoot, Chillies, Garlic", 300, 25, 5, 20, "Dinner"),
        ("Apong", "Rice, Fermented Yeast", 150, 2, 30, 0, "Snack"),
        ("Bamboo Shoot Fry", "Bamboo Shoot, Spices, Garlic", 100, 2, 15, 3, "Side"),
        ("Kharzi", "Rice, Chicken, Spices, Herbs", 400, 20, 50, 15, "Lunch"),
        ("Mung Bean Soup", "Mung Beans, Ginger, Garlic, Spices", 150, 8, 20, 2, "Side"),
        ("Pork with Bamboo", "Pork, Bamboo Shoot, Chillies", 350, 22, 5, 25, "Dinner"),
        ("Zan", "Millet, Water, Fermented Yeast", 200, 3, 40, 2, "Snack"),
        ("Fish Stew", "Fish, Herbs, Spices, Ginger", 250, 18, 10, 15, "Dinner"),
        ("Chicken with Herbs", "Chicken, Local Herbs, Spices", 300, 25, 5, 18, "Dinner"),
        ("Oying", "Mixed Vegetables, Bamboo Shoot, Ginger", 130, 3, 18, 4, "Side"),
        ("Ngatok", "Fish, Local Spices, Banana Leaf", 280, 20, 8, 15, "Dinner"),
        ("Pe Hak", "Fermented Soybeans, Chillies, Garlic", 140, 7, 12, 6, "Side"),
        ("Amra", "Pork, Dry Chillies, Smoked Spices", 420, 28, 5, 30, "Dinner"),
        ("Rice Cake", "Sticky Rice, Salt, Spices", 250, 4, 45, 5, "Snack"),
        ("Yom Pat", "Wild Greens, Garlic, Spices", 120, 3, 15, 4, "Side"),
        ("Mithun Curry", "Mithun Meat, Ginger, Chillies", 450, 32, 10, 28, "Dinner"),
        ("Etting", "Fermented Bamboo Shoot, Spices", 90, 2, 10, 3, "Side"),
        ("Chicken Ngathu", "Chicken, King Chilli, Bamboo Shoot", 360, 26, 8, 22, "Dinner"),
        ("Millet Porridge", "Millet, Milk, Jaggery", 300, 6, 50, 8, "Breakfast"),
        ("Smoked Fish Fry", "Fish, Spices, Smoke Flavor", 270, 19, 5, 18, "Dinner"),
        ("Tapyo", "Dried Fish, Chillies, Salt", 110, 8, 2, 6, "Side"),
        ("Pork Anishi", "Pork, Fermented Yam Leaves, Spices", 400, 25, 6, 28, "Dinner"),
        ("Rice Porridge", "Rice, Ginger, Local Herbs", 220, 4, 40, 3, "Breakfast"),
        ("Goat Stew", "Goat Meat, Spices, Bamboo Shoot", 380, 30, 8, 25, "Dinner")
    ],
    "Assam": [
        ("Masor Tenga", "Fish, Tomatoes, Lemon, Spices", 200, 15, 10, 12, "Dinner"),
        ("Aloo Pitika", "Potatoes, Mustard Oil, Onions, Chillies", 150, 3, 25, 5, "Side"),
        ("Pitha", "Rice Flour, Coconut, Jaggery", 300, 4, 50, 8, "Snack"),
        ("Duck Curry", "Duck, Spices, Onions, Garlic", 400, 28, 10, 25, "Dinner"),
        ("Khar", "Raw Papaya, Pulses, Spices", 150, 5, 20, 3, "Side"),
        ("Bamboo Shoot Curry", "Bamboo Shoot, Spices, Ginger", 100, 2, 15, 3, "Side"),
        ("Pork with Bamboo", "Pork, Bamboo Shoot, Chillies", 350, 22, 5, 25, "Dinner"),
        ("Jolpan", "Rice, Curd, Jaggery", 250, 5, 40, 5, "Breakfast"),
        ("Chicken with Banana Flower", "Chicken, Banana Flower, Spices", 300, 20, 10, 15, "Dinner"),
        ("Fish Fry", "Fish, Spices, Mustard Oil", 200, 15, 5, 12, "Dinner"),
        ("Bilahi Maas", "Fish, Tomatoes, Turmeric, Spices", 220, 16, 8, 12, "Dinner"),
        ("Koldil Bhaji", "Banana Flower, Spices, Mustard Oil", 140, 3, 18, 6, "Side"),
        ("Narzi", "Rice, Pork, Local Herbs", 380, 20, 50, 15, "Lunch"),
        ("Ou Tenga", "Elephant Apple, Spices, Lentils", 130, 4, 20, 2, "Side"),
        ("Pani Pitha", "Rice Flour, Water, Jaggery", 280, 4, 45, 8, "Snack"),
        ("Tilor Laru", "Sesame Seeds, Jaggery", 350, 6, 50, 12, "Snack"),
        ("Mati Mahor Dal", "Black Lentils, Spices, Ginger", 160, 7, 22, 3, "Side"),
        ("Kumura Aloo", "Sweet Potato, Mustard Oil, Spices", 180, 3, 30, 5, "Side"),
        ("Bora Saul", "Sticky Rice, Milk, Sugar", 320, 6, 55, 8, "Snack"),
        ("Goat Curry", "Goat Meat, Spices, Onions", 420, 30, 10, 28, "Dinner"),
        ("Lai Xaak", "Mustard Greens, Garlic, Spices", 120, 3, 15, 4, "Side"),
        ("Misa Maas", "Prawns, Spices, Bamboo Shoot", 260, 20, 6, 16, "Dinner"),
        ("Sunga Pitha", "Rice Flour, Coconut, Spices", 300, 5, 50, 8, "Snack"),
        ("Kon Bilahi Chutney", "Roasted Tomato, Chillies, Garlic", 100, 2, 12, 4, "Side"),
        ("Chicken Tenga", "Chicken, Lemon, Spices", 340, 25, 8, 20, "Dinner"),
        ("Posola Bhaji", "Banana Stem, Spices, Oil", 150, 3, 20, 5, "Side"),
        ("Khorisa", "Fermented Bamboo Shoot, Chillies", 90, 2, 10, 3, "Side"),
        ("Duck Roast", "Duck, Spices, Mustard Oil", 450, 30, 5, 32, "Dinner"),
        ("Guti Aloo", "Baby Potatoes, Spices, Oil", 170, 3, 25, 6, "Side"),
        ("Kumol Saul", "Soft Rice, Curd, Spices", 250, 5, 45, 5, "Breakfast")
    ],
    "Bihar": [
        ("Litti Chokha", "Wheat Flour, Brinjal, Tomatoes, Spices", 400, 10, 60, 12, "Lunch"),
        ("Sattu Paratha", "Wheat Flour, Sattu, Spices", 350, 12, 50, 10, "Breakfast"),
        ("Chana Ghugni", "Chickpeas, Onions, Spices", 200, 8, 30, 5, "Snack"),
        ("Bihari Kebab", "Mutton, Spices, Yogurt", 450, 30, 5, 30, "Dinner"),
        ("Dal Puri", "Wheat Flour, Lentils, Spices", 300, 10, 45, 8, "Lunch"),
        ("Thekua", "Wheat Flour, Jaggery, Ghee", 400, 5, 60, 15, "Snack"),
        ("Khichdi", "Rice, Lentils, Spices", 250, 8, 40, 5, "Lunch"),
        ("Fish Curry", "Fish, Mustard, Spices", 300, 20, 10, 15, "Dinner"),
        ("Mutton Curry", "Mutton, Onions, Spices", 400, 28, 10, 25, "Dinner"),
        ("Pua", "Wheat Flour, Milk, Sugar", 350, 6, 50, 12, "Snack"),
        ("Kadhi Bari", "Besan, Yogurt, Spices", 280, 10, 35, 12, "Lunch"),
        ("Tilkut", "Sesame Seeds, Jaggery, Ghee", 320, 6, 30, 18, "Snack"),
        ("Malpua", "Wheat Flour, Milk, Sugar, Fennel", 400, 5, 55, 20, "Snack"),
        ("Balushahi", "Maida, Ghee, Sugar", 450, 4, 50, 25, "Snack"),
        ("Anarsa", "Rice Flour, Jaggery, Poppy Seeds", 300, 4, 40, 15, "Snack"),
        ("Pedakiya", "Wheat Flour, Suji, Coconut, Sugar", 380, 6, 45, 18, "Snack"),
        ("Chana Samosa", "Wheat Flour, Chickpeas, Spices", 320, 8, 35, 15, "Snack"),
        ("Aloo Kachalu", "Potatoes, Tamarind, Spices", 200, 4, 25, 10, "Snack"),
        ("Dhuska", "Rice, Chana Dal, Spices", 350, 10, 40, 20, "Breakfast"),
        ("Choora Dahi", "Flattened Rice, Yogurt, Sugar", 250, 6, 35, 8, "Breakfast"),
        ("Laung Latika", "Maida, Khoya, Ghee, Clove", 370, 7, 45, 22, "Snack"),
        ("Khaja", "Maida, Sugar, Ghee", 360, 4, 40, 20, "Snack"),
        ("Bajka", "Vegetables, Besan, Spices", 300, 6, 30, 16, "Snack"),
        ("Besan ki Sabzi", "Besan, Spices, Tomatoes", 260, 10, 20, 12, "Lunch"),
        ("Bhooja", "Puffed Rice, Peanuts, Spices", 200, 5, 25, 10, "Snack"),
        ("Sattu Drink", "Sattu, Water, Lemon, Spices", 150, 10, 15, 4, "Breakfast"),
        ("Korma", "Vegetables/Mutton, Spices, Yogurt", 400, 25, 15, 22, "Dinner"),
        ("Seviyan Kheer", "Vermicelli, Milk, Sugar", 280, 7, 35, 12, "Dessert"),
        ("Makhan Roti", "Wheat Flour, White Butter, Salt", 300, 6, 40, 14, "Lunch"),
        ("Handia", "Rice, Herbal Fermentation", 120, 2, 20, 1, "Beverage")
    ],
    "Chattisgarh": [
        ("Chila", "Rice Flour, Urad Dal, Spices", 200, 6, 30, 5, "Breakfast"),
        ("Fara", "Rice Flour, Lentils, Spices", 250, 8, 40, 5, "Snack"),
        ("Bafauri", "Chana Dal, Spices, Ginger", 150, 6, 20, 3, "Snack"),
        ("Muthia", "Rice Flour, Vegetables, Spices", 200, 4, 30, 5, "Side"),
        ("Dehrori", "Rice Flour, Milk, Sugar", 400, 5, 60, 15, "Snack"),
        ("Aamat", "Bamboo Shoot, Lentils, Spices", 150, 5, 20, 3, "Side"),
        ("Bore Baasi", "Rice, Curd, Spices", 200, 4, 35, 5, "Breakfast"),
        ("Angakar Roti", "Rice Flour, Spices", 250, 5, 40, 5, "Breakfast"),
        ("Petha", "Rice Flour, Jaggery, Ghee", 350, 4, 50, 12, "Snack"),
        ("Red Ant Chutney", "Red Ants, Chillies, Garlic", 50, 2, 5, 2, "Side"),
        ("Dubki Kadhi", "Besan, Yogurt, Spices", 220, 7, 25, 10, "Lunch"),
        ("Tilgur", "Sesame Seeds, Jaggery", 300, 5, 35, 15, "Snack"),
        ("Thethri", "Rice Flour, Spices, Oil", 270, 4, 30, 12, "Snack"),
        ("Khurma", "Wheat Flour, Sugar, Ghee", 400, 4, 55, 18, "Snack"),
        ("Chousela Roti", "Rice Flour, Oil", 240, 5, 38, 6, "Lunch"),
        ("Bhajia", "Vegetables, Besan, Spices", 280, 5, 30, 14, "Snack"),
        ("Mahuwa Laddu", "Mahuwa Flowers, Jaggery, Rice", 330, 3, 50, 12, "Snack"),
        ("Rakhia Badi", "Urad Dal, Spices, Sun-dried", 180, 8, 20, 6, "Side"),
        ("Kochar Bhaji", "Kochar Leaves, Mustard, Spices", 100, 3, 10, 4, "Side"),
        ("Bhujiya", "Potatoes, Spices, Oil", 220, 3, 30, 12, "Snack"),
        ("Bhajiya Kadhi", "Pakoras, Yogurt, Besan", 250, 7, 20, 10, "Lunch"),
        ("Phara Idli", "Rice Flour, Lentils, Spices", 200, 6, 35, 4, "Breakfast"),
        ("Charota", "Jackfruit, Mustard, Spices", 180, 4, 20, 7, "Side"),
        ("Kanda Bhaji", "Onions, Besan, Spices", 240, 4, 28, 13, "Snack"),
        ("Kurmura Laddu", "Puffed Rice, Jaggery", 180, 3, 30, 5, "Snack"),
        ("Bara", "Urad Dal, Spices, Oil", 300, 8, 30, 15, "Snack"),
        ("Kochai Patta Curry", "Colocasia Leaves, Tamarind, Spices", 160, 4, 20, 6, "Lunch"),
        ("Basi Bhaat", "Fermented Rice, Water, Salt", 100, 2, 15, 1, "Breakfast"),
        ("Chech Bhaji", "Green Leafy Veg, Garlic, Spices", 120, 3, 10, 5, "Side")
    ],
    "Goa": [
        ("Fish Curry", "Fish, Coconut, Tamarind, Spices", 300, 20, 10, 15, "Dinner"),
        ("Prawn Balchao", "Prawns, Vinegar, Spices", 250, 18, 5, 15, "Dinner"),
        ("Chicken Xacuti", "Chicken, Coconut, Spices", 400, 25, 10, 20, "Dinner"),
        ("Bebinca", "Coconut Milk, Flour, Sugar, Eggs", 500, 8, 70, 20, "Snack"),
        ("Pork Vindaloo", "Pork, Vinegar, Spices", 450, 28, 10, 30, "Dinner"),
        ("Sannas", "Rice, Coconut, Yeast", 200, 4, 35, 5, "Breakfast"),
        ("Goan Pao", "Wheat Flour, Yeast", 150, 5, 25, 2, "Breakfast"),
        ("Sorpotel", "Pork, Liver, Vinegar, Spices", 400, 25, 10, 25, "Dinner"),
        ("Fish Recheado", "Fish, Red Chillies, Spices", 300, 20, 5, 15, "Dinner"),
        ("Prawn Rissóis", "Prawns, Flour, Spices", 250, 15, 20, 10, "Snack"),
        ("Goan Kismur", "Dry Fish, Coconut, Onions, Spices", 180, 12, 10, 8, "Side"),
        ("Mutton Xacuti", "Mutton, Coconut, Poppy Seeds, Spices", 450, 30, 12, 28, "Dinner"),
        ("Caldo Verde", "Spinach, Potatoes, Onion, Garlic", 180, 6, 20, 8, "Soup"),
        ("Tonak", "Black Chickpeas, Spices, Coconut", 220, 10, 25, 10, "Breakfast"),
        ("Khatkhate", "Mixed Vegetables, Coconut, Spices", 200, 6, 28, 9, "Lunch"),
        ("Alle Belle", "Coconut, Jaggery, Flour", 300, 4, 40, 12, "Snack"),
        ("Dodol", "Coconut Milk, Jaggery, Rice Flour", 350, 3, 45, 15, "Snack"),
        ("Goan Nevri", "Flour, Coconut, Sugar, Cardamom", 330, 4, 40, 16, "Snack"),
        ("Choris Pao", "Goan Sausage, Bread, Spices", 400, 20, 35, 22, "Breakfast"),
        ("Patal Bhaji", "White Peas, Onion, Tomato, Spices", 220, 8, 30, 8, "Breakfast"),
        ("Goan Banana Fritters", "Banana, Flour, Sugar", 280, 3, 40, 12, "Snack"),
        ("Tizann", "Nachni (Ragi), Jaggery, Coconut Milk", 200, 5, 30, 7, "Breakfast"),
        ("Batte Pav", "Mashed Peas, Bread, Spices", 300, 6, 40, 12, "Breakfast"),
        ("Goan Crab Curry", "Crab, Coconut, Tamarind, Spices", 320, 25, 10, 16, "Lunch"),
        ("Sungta Hooman", "Prawns, Tamarind, Coconut", 280, 20, 8, 14, "Dinner"),
        ("Tisreo Sukhem", "Clams, Coconut, Spices", 250, 18, 6, 12, "Side"),
        ("Bangda Uddamethi", "Mackerel, Methi Seeds, Spices", 290, 22, 7, 13, "Dinner"),
        ("Sol Kadhi", "Coconut Milk, Kokum, Garlic", 100, 2, 6, 6, "Beverage"),
        ("Ross Omelette", "Eggs, Spicy Gravy, Bread", 350, 18, 25, 18, "Dinner"),
        ("Pineapple Sheera", "Rava, Pineapple, Ghee, Sugar", 360, 4, 45, 15, "Dessert")
    ],
    "Gujarat": [
        ("Dhokla", "Gram Flour, Yogurt, Spices", 150, 6, 20, 5, "Breakfast"),
        ("Thepla", "Wheat Flour, Fenugreek, Spices", 200, 6, 30, 5, "Breakfast"),
        ("Undhiyu", "Mixed Vegetables, Spices, Coconut", 300, 8, 40, 10, "Lunch"),
        ("Khandvi", "Gram Flour, Yogurt, Spices", 100, 4, 15, 3, "Snack"),
        ("Fafda", "Gram Flour, Spices, Oil", 200, 5, 25, 8, "Snack"),
        ("Jalebi", "Wheat Flour, Sugar Syrup", 400, 3, 60, 15, "Snack"),
        ("Gujarati Kadhi", "Yogurt, Gram Flour, Spices", 150, 4, 20, 5, "Side"),
        ("Shrikhand", "Yogurt, Sugar, Saffron", 300, 8, 40, 10, "Snack"),
        ("Patra", "Colocasia Leaves, Gram Flour, Spices", 200, 5, 25, 8, "Snack"),
        ("Khichu", "Rice Flour, Spices, Oil", 150, 3, 25, 3, "Snack"),
        ("Handvo", "Rice, Lentils, Vegetables", 250, 10, 35, 8, "Breakfast"),
        ("Sev Tameta", "Tomato, Sev, Spices", 220, 4, 20, 10, "Lunch"),
        ("Bhaat Na Rasawala Muthia", "Rice, Gram Flour, Spices", 230, 6, 35, 7, "Lunch"),
        ("Dal Dhokli", "Wheat Dough, Toor Dal, Spices", 280, 10, 40, 9, "Lunch"),
        ("Lilva Kachori", "Green Peas, Flour, Spices", 300, 6, 30, 12, "Snack"),
        ("Moong Dal Chilla", "Moong Dal, Spices", 180, 10, 20, 5, "Breakfast"),
        ("Bhakri", "Wheat Flour, Oil", 250, 5, 30, 10, "Breakfast"),
        ("Sev Usal", "Peas, Sev, Spices", 300, 7, 35, 12, "Snack"),
        ("Mag Ni Dal", "Moong Dal, Spices", 180, 9, 25, 6, "Lunch"),
        ("Batata Nu Shaak", "Potatoes, Spices", 200, 3, 30, 8, "Lunch"),
        ("Rotlo", "Millet Flour, Ghee", 220, 4, 30, 7, "Dinner"),
        ("Khatti Meethi Dal", "Toor Dal, Jaggery, Tamarind", 250, 8, 35, 7, "Lunch"),
        ("Mohanthal", "Gram Flour, Ghee, Sugar", 400, 5, 45, 18, "Dessert"),
        ("Sukhdi", "Wheat Flour, Jaggery, Ghee", 350, 4, 40, 15, "Snack"),
        ("Tuver Ringan Nu Shaak", "Brinjal, Toor Dal, Spices", 240, 7, 30, 10, "Lunch"),
        ("Ringan No Oro", "Roasted Brinjal, Spices", 180, 4, 20, 8, "Side"),
        ("Lasaniya Bataka", "Garlic, Potatoes, Spices", 210, 3, 28, 9, "Lunch"),
        ("Bataka Poha", "Flattened Rice, Potatoes, Spices", 220, 4, 30, 7, "Breakfast"),
        ("Chorafali", "Urad Flour, Spices, Oil", 270, 5, 25, 14, "Snack"),
        ("Ghari", "Flour, Mawa, Sugar", 500, 6, 60, 22, "Dessert")
    ],  
    "Haryana": [
        ("Bajra Khichdi", "Pearl Millet, Lentils, Spices", 300, 10, 50, 5, "Lunch"),
        ("Kachri Ki Sabzi", "Kachri, Spices, Oil", 150, 2, 20, 5, "Side"),
        ("Hara Cholia", "Green Chickpeas, Spices", 200, 8, 30, 5, "Side"),
        ("Rabri", "Milk, Sugar, Nuts", 400, 10, 50, 15, "Snack"),
        ("Gajar Ka Halwa", "Carrots, Milk, Sugar, Ghee", 500, 8, 60, 20, "Snack"),
        ("Kadhi Pakora", "Yogurt, Gram Flour, Spices", 200, 6, 25, 8, "Lunch"),
        ("Methi Gajar", "Fenugreek, Carrots, Spices", 150, 3, 20, 5, "Side"),
        ("Aloo Paratha", "Wheat Flour, Potatoes, Spices", 350, 8, 50, 10, "Breakfast"),
        ("Lassi", "Yogurt, Sugar, Water", 200, 6, 30, 5, "Snack"),
        ("Churma", "Wheat Flour, Jaggery, Ghee", 400, 6, 60, 15, "Snack"),
        ("Bajra Roti", "Pearl Millet Flour, Ghee", 250, 6, 35, 8, "Breakfast"),
        ("Besan Masala Roti", "Gram Flour, Spices, Wheat Flour", 270, 8, 30, 10, "Breakfast"),
        ("Bathua Raita", "Bathua Leaves, Yogurt, Spices", 120, 4, 10, 4, "Side"),
        ("Singri Ki Sabzi", "Ker-Singri, Spices", 180, 5, 15, 8, "Side"),
        ("Ghee Shakkar", "Ghee, Jaggery, Wheat", 300, 3, 40, 12, "Snack"),
        ("Thandai", "Milk, Nuts, Spices", 250, 6, 20, 10, "Beverage"),
        ("Missi Roti", "Wheat Flour, Gram Flour, Spices", 240, 6, 30, 7, "Breakfast"),
        ("Ghevar", "Refined Flour, Sugar Syrup, Ghee", 500, 5, 65, 22, "Dessert"),
        ("Kachi Lassi", "Buttermilk, Cumin, Salt", 90, 3, 8, 2, "Beverage"),
        ("Mooli Paratha", "Wheat Flour, Radish, Spices", 320, 7, 45, 8, "Breakfast"),
        ("Til Ke Laddu", "Sesame Seeds, Jaggery", 280, 4, 30, 12, "Snack"),
        ("Bhaat (Desi Style Rice)", "Rice, Ghee, Cumin", 250, 4, 45, 7, "Lunch"),
        ("Saag", "Mustard Greens, Spices", 200, 5, 15, 10, "Lunch"),
        ("Makki Ki Roti", "Maize Flour, Ghee", 230, 4, 30, 9, "Lunch"),
        ("Besan Cheela", "Gram Flour, Spices, Veggies", 200, 8, 25, 6, "Breakfast"),
        ("Chana Masala", "Chickpeas, Onion, Spices", 260, 10, 30, 10, "Lunch"),
        ("Dahi Bhalla", "Urad Dal, Yogurt, Spices", 320, 9, 35, 12, "Snack"),
        ("Amaranth Kheer", "Amaranth, Milk, Sugar", 300, 6, 40, 10, "Dessert"),
        ("Amla Murabba", "Amla, Sugar, Cardamom", 150, 1, 35, 2, "Snack"),
        ("Besan Pinni", "Gram Flour, Ghee, Dry Fruits", 400, 6, 35, 20, "Dessert")
    ],
    "Himachal Pradesh": [
        ("Dham", "Rice, Lentils, Yogurt, Spices", 400, 10, 60, 10, "Lunch"),
        ("Siddu", "Wheat Flour, Yeast, Spices", 300, 8, 50, 5, "Breakfast"),
        ("Chha Gosht", "Mutton, Yogurt, Spices", 450, 30, 10, 30, "Dinner"),
        ("Babru", "Wheat Flour, Black Gram, Spices", 250, 8, 40, 5, "Breakfast"),
        ("Kullu Trout", "Fish, Spices, Lemon", 300, 20, 5, 15, "Dinner"),
        ("Madra", "Chickpeas, Yogurt, Spices", 200, 8, 30, 5, "Lunch"),
        ("Bhey", "Lotus Stem, Spices, Oil", 150, 3, 20, 5, "Side"),
        ("Aktori", "Buckwheat Flour, Spices", 200, 5, 35, 3, "Breakfast"),
        ("Patande", "Wheat Flour, Milk, Sugar", 350, 6, 50, 12, "Snack"),
        ("Sepu Badi", "Urad Dal, Spices, Yogurt", 200, 8, 25, 5, "Side"),
        ("Chana Madra", "Kabuli Chana, Yogurt, Spices", 250, 9, 25, 6, "Lunch"),
        ("Tudkiya Bhath", "Rice, Lentils, Potatoes, Spices", 300, 10, 45, 8, "Lunch"),
        ("Mittha", "Rice, Raisins, Dry Fruits, Sugar", 350, 4, 60, 10, "Dessert"),
        ("Khatta", "Pumpkin, Tamarind, Spices", 200, 4, 30, 6, "Side"),
        ("Telia Maah", "Urad Dal, Ghee, Spices", 250, 8, 20, 10, "Dinner"),
        ("Chana Dal Pulao", "Chana Dal, Rice, Spices", 300, 10, 50, 6, "Lunch"),
        ("Bhaturu", "Wheat Flour, Yeast, Ghee", 280, 7, 35, 7, "Breakfast"),
        ("Kachori Himachali", "Wheat Flour, Urad Dal, Spices", 300, 8, 40, 10, "Snack"),
        ("Makki Ki Roti", "Maize Flour, Ghee", 230, 5, 35, 6, "Lunch"),
        ("Sarson Ka Saag", "Mustard Greens, Spices, Ghee", 200, 6, 20, 8, "Lunch"),
        ("Luchi", "Refined Flour, Ghee", 300, 4, 40, 15, "Breakfast"),
        ("Baadi", "Wheat Flour, Ghee, Buttermilk", 250, 6, 30, 8, "Lunch"),
        ("Auriya Kadoo", "Pumpkin, Mustard Seeds, Spices", 180, 3, 25, 5, "Side"),
        ("Pahari Kadhi", "Buttermilk, Besan, Spices", 200, 5, 20, 6, "Lunch"),
        ("Chouck", "Curd, Mustard Seeds, Spices", 150, 3, 10, 5, "Side"),
        ("Chamba Style Rajma", "Kidney Beans, Spices", 300, 10, 40, 6, "Lunch"),
        ("Sidu with Ghee", "Wheat Flour, Ghee, Spices", 350, 8, 50, 12, "Dinner"),
        ("Beduan Roti", "Wheat Flour, Black Gram Paste", 320, 7, 40, 10, "Dinner"),
        ("Bhaang Ki Chutney", "Hemp Seeds, Mint, Spices", 100, 2, 5, 3, "Side"),
        ("Meetha Bhaat", "Sweet Rice, Sugar, Cardamom", 300, 5, 50, 8, "Snack")
    ],
    "Jharkhand": [
        ("Dhuska", "Rice, Urad Dal, Spices", 200, 6, 30, 5, "Breakfast"),
        ("Rugda", "Mushrooms, Spices, Oil", 150, 5, 15, 5, "Side"),
        ("Chilka Roti", "Rice Flour, Spices", 200, 4, 35, 3, "Breakfast"),
        ("Handia", "Rice, Fermented Herbs", 150, 2, 30, 0, "Snack"),
        ("Litti", "Wheat Flour, Sattu, Spices", 400, 10, 60, 12, "Lunch"),
        ("Pitha", "Rice Flour, Jaggery, Coconut", 300, 4, 50, 8, "Snack"),
        ("Bamboo Shoot Sabzi", "Bamboo Shoot, Spices", 100, 2, 15, 3, "Side"),
        ("Chicken Curry", "Chicken, Spices, Onions", 350, 25, 10, 20, "Dinner"),
        ("Fish Curry", "Fish, Mustard, Spices", 300, 20, 10, 15, "Dinner"),
        ("Thekua", "Wheat Flour, Jaggery, Ghee", 400, 5, 60, 15, "Snack"),
        ("Koinar Saag", "Koinar Leaves, Spices", 120, 3, 10, 5, "Side"),
        ("Sanai Phool Bharta", "Sesbania Flowers, Mustard Oil, Spices", 130, 4, 8, 6, "Side"),
        ("Tilkut", "Sesame Seeds, Jaggery", 300, 6, 40, 12, "Snack"),
        ("Malpua", "Flour, Milk, Sugar", 350, 5, 50, 15, "Snack"),
        ("Aloo Chokha", "Potatoes, Spices, Mustard Oil", 180, 3, 25, 6, "Side"),
        ("Maduwa Roti", "Finger Millet Flour, Ghee", 200, 5, 30, 5, "Breakfast"),
        ("Dumar Rasa", "Jackfruit, Spices, Oil", 250, 4, 20, 10, "Lunch"),
        ("Kudrum Bharta", "Ivy Gourd, Mustard Oil, Spices", 160, 3, 15, 7, "Side"),
        ("Chana Saag", "Chickpea Leaves, Spices", 140, 6, 12, 4, "Side"),
        ("Baiganee Bharta", "Roasted Brinjal, Spices", 180, 3, 15, 5, "Side"),
        ("Roti with Chutney", "Wheat Flour, Tomato, Garlic", 220, 5, 30, 6, "Breakfast"),
        ("Seema Sag", "Water Leaf, Mustard Oil, Garlic", 130, 2, 10, 5, "Side"),
        ("Bhunjia", "Puffed Rice, Mustard Oil, Spices", 150, 3, 30, 2, "Snack"),
        ("Gulgula", "Wheat Flour, Jaggery, Fennel", 280, 4, 40, 10, "Snack"),
        ("Mushroom Bharta", "Local Mushrooms, Mustard Oil, Spices", 200, 7, 15, 10, "Dinner"),
        ("Rahar Dal", "Pigeon Pea Lentils, Spices", 250, 10, 35, 6, "Lunch"),
        ("Pua", "Wheat Flour, Sugar, Milk", 300, 4, 45, 12, "Snack"),
        ("Kusli", "Refined Flour, Ghee, Sugar", 350, 3, 50, 18, "Snack"),
        ("Chura Dahi", "Flattened Rice, Curd, Sugar", 200, 4, 35, 5, "Breakfast"),
        ("Khichdi with Chokha", "Rice, Lentils, Vegetables", 350, 9, 45, 10, "Lunch")
    ],
    "Karnataka": [
        ("Bisi Bele Bath", "Rice, Lentils, Vegetables, Spices", 400, 10, 60, 10, "Lunch"),
        ("Ragi Mudde", "Ragi Flour, Water", 150, 4, 30, 2, "Lunch"),
        ("Mysore Pak", "Gram Flour, Sugar, Ghee", 500, 5, 70, 20, "Snack"),
        ("Dosa", "Rice, Urad Dal, Spices", 200, 6, 30, 5, "Breakfast"),
        ("Chicken Sukka", "Chicken, Coconut, Spices", 350, 25, 10, 20, "Dinner"),
        ("Obbattu", "Wheat Flour, Jaggery, Lentils", 400, 8, 60, 12, "Snack"),
        ("Kesari Bath", "Semolina, Sugar, Ghee, Saffron", 450, 6, 70, 15, "Snack"),
        ("Maddur Vada", "Rice Flour, Semolina, Spices", 200, 5, 25, 8, "Snack"),
        ("Kori Gassi", "Chicken, Coconut, Spices", 400, 25, 10, 20, "Dinner"),
        ("Akki Roti", "Rice Flour, Spices, Vegetables", 200, 4, 35, 5, "Breakfast"),
        ("Neer Dosa", "Rice, Coconut, Water", 180, 3, 30, 3, "Breakfast"),
        ("Chitranna", "Rice, Turmeric, Mustard Seeds", 250, 4, 45, 6, "Lunch"),
        ("Uppittu (Upma)", "Semolina, Vegetables, Spices", 200, 5, 35, 6, "Breakfast"),
        ("Vangi Bath", "Rice, Brinjal, Spices", 300, 6, 50, 8, "Lunch"),
        ("Rave Unde", "Semolina, Jaggery, Coconut", 280, 4, 40, 10, "Snack"),
        ("Mangalore Buns", "Banana, Flour, Yogurt", 300, 4, 45, 10, "Snack"),
        ("Kharabath", "Semolina, Vegetables, Spices", 250, 5, 35, 7, "Breakfast"),
        ("Soppu Saaru", "Green Leafy Veg, Dal, Spices", 200, 6, 20, 4, "Side"),
        ("Pundi", "Rice Balls, Coconut, Spices", 220, 4, 30, 6, "Breakfast"),
        ("Haalbai", "Coconut, Jaggery, Rice Flour", 350, 3, 50, 15, "Snack"),
        ("Bonda Soup", "Fried Gram Balls, Spiced Soup", 300, 8, 40, 12, "Snack"),
        ("Gojju Avalakki", "Flattened Rice, Tamarind, Spices", 230, 3, 35, 5, "Breakfast"),
        ("Menthe Dosa", "Fenugreek, Rice, Dal", 210, 6, 30, 4, "Breakfast"),
        ("Avarekalu Saaru", "Hyacinth Beans, Spices", 240, 10, 25, 8, "Dinner"),
        ("Rotti with Ennegai", "Roti, Brinjal Curry", 350, 8, 45, 10, "Lunch"),
        ("Sajjige", "Semolina, Milk, Sugar", 260, 4, 40, 8, "Snack"),
        ("Thuppa Dosa", "Rice, Ghee, Urad Dal", 300, 5, 40, 10, "Breakfast"),
        ("Nuchinunde", "Toor Dal, Coconut, Spices", 220, 7, 30, 6, "Snack"),
        ("Majjige Huli", "Buttermilk, Vegetables, Spices", 180, 3, 20, 5, "Side"),
        ("Jackfruit Idli", "Jackfruit, Rice, Coconut", 250, 4, 35, 8, "Snack")
    ],
    "Kerala": [
        ("Appam", "Rice, Coconut, Yeast", 200, 4, 35, 5, "Breakfast"),
        ("Fish Molee", "Fish, Coconut Milk, Spices", 300, 20, 10, 15, "Dinner"),
        ("Puttu", "Rice Flour, Coconut", 150, 3, 25, 3, "Breakfast"),
        ("Beef Fry", "Beef, Coconut, Spices", 400, 30, 5, 25, "Dinner"),
        ("Sadya", "Rice, Mixed Vegetables, Spices", 500, 10, 80, 10, "Lunch"),
        ("Kerala Parotta", "Wheat Flour, Oil", 300, 6, 50, 8, "Dinner"),
        ("Prawn Curry", "Prawns, Coconut, Spices", 350, 22, 10, 20, "Dinner"),
        ("Banana Chips", "Banana, Coconut Oil", 200, 2, 30, 8, "Snack"),
        ("Thalassery Biryani", "Rice, Chicken, Spices", 600, 25, 80, 20, "Lunch"),
        ("Jackfruit Payasam", "Jackfruit, Coconut Milk, Jaggery", 400, 5, 60, 12, "Snack"),
        ("Idiyappam", "Rice Flour, Coconut", 180, 3, 35, 3, "Breakfast"),
        ("Nadan Kozhi Curry", "Chicken, Spices, Coconut Oil", 400, 28, 10, 20, "Dinner"),
        ("Avial", "Mixed Vegetables, Coconut, Curd", 250, 5, 20, 10, "Side"),
        ("Sambar", "Lentils, Vegetables, Tamarind", 200, 8, 25, 5, "Side"),
        ("Olan", "Ash Gourd, Red Beans, Coconut Milk", 150, 3, 15, 6, "Side"),
        ("Kaalan", "Yam, Curd, Coconut, Spices", 180, 4, 20, 6, "Side"),
        ("Theeyal", "Coconut, Tamarind, Spices", 200, 3, 25, 8, "Side"),
        ("Pazham Pori", "Banana, Maida, Sugar", 300, 2, 50, 10, "Snack"),
        ("Unniyappam", "Rice, Banana, Jaggery", 350, 5, 45, 12, "Snack"),
        ("Neyyappam", "Rice Flour, Jaggery, Ghee", 360, 4, 50, 14, "Snack"),
        ("Kappa Puzhukku", "Tapioca, Coconut, Spices", 250, 3, 40, 6, "Snack"),
        ("Chakka Varattiyathu", "Jackfruit, Jaggery, Ghee", 300, 4, 50, 10, "Snack"),
        ("Meen Peera", "Fish, Coconut, Tamarind", 300, 18, 10, 12, "Side"),
        ("Erachi Varutharacha Curry", "Beef, Roasted Coconut, Spices", 450, 30, 5, 22, "Dinner"),
        ("Chemmeen Roast", "Prawns, Onions, Coconut Oil", 350, 22, 10, 18, "Dinner"),
        ("Kozhukatta", "Rice Flour, Coconut, Jaggery", 280, 3, 40, 10, "Snack"),
        ("Idli with Coconut Chutney", "Rice, Dal, Coconut", 200, 6, 30, 5, "Breakfast"),
        ("Pathiri", "Rice Flour, Water", 180, 2, 35, 2, "Dinner"),
        ("Palada Payasam", "Rice, Milk, Sugar", 400, 6, 60, 12, "Snack"),
        ("Ada Pradhaman", "Rice Ada, Jaggery, Coconut Milk", 450, 5, 65, 15, "Snack") 
    ],
    "Madya Pradesh": [
        ("Poha", "Flattened Rice, Peanuts, Spices", 200, 4, 35, 5, "Breakfast"),
        ("Bhutte Ka Kees", "Corn, Milk, Spices", 250, 5, 40, 8, "Snack"),
        ("Dal Bafla", "Wheat Flour, Lentils, Spices", 400, 10, 60, 10, "Lunch"),
        ("Kusli", "Wheat Flour, Jaggery, Coconut", 350, 6, 50, 12, "Snack"),
        ("Mawa Bati", "Milk Solids, Sugar, Ghee", 500, 8, 60, 20, "Snack"),
        ("Palak Puri", "Wheat Flour, Spinach, Spices", 300, 8, 45, 8, "Breakfast"),
        ("Bhutte Ki Sabzi", "Corn, Spices, Oil", 200, 4, 30, 5, "Side"),
        ("Chicken Korma", "Chicken, Yogurt, Spices", 400, 25, 10, 20, "Dinner"),
        ("Jalebi", "Wheat Flour, Sugar Syrup", 400, 3, 60, 15, "Snack"),
        ("Sabudana Khichdi", "Sago, Peanuts, Spices", 250, 4, 40, 8, "Breakfast"),
        ("Keema Pulao", "Minced Meat, Rice, Spices", 450, 20, 50, 15, "Lunch"),
        ("Seekh Kebabs", "Minced Meat, Spices, Skewered", 350, 25, 5, 20, "Snack"),
        ("Bhopali Gosht Korma", "Mutton, Yogurt, Spices", 500, 30, 10, 25, "Dinner"),
        ("Chakki Ki Shaak", "Wheat Dough, Gravy, Spices", 300, 10, 30, 10, "Lunch"),
        ("Indori Namkeen", "Mixture, Spices, Lentils", 250, 6, 35, 12, "Snack"),
        ("Indori Sev", "Gram Flour, Oil, Spices", 300, 4, 20, 15, "Snack"),
        ("Garadu", "Yam, Spices, Oil", 200, 3, 25, 10, "Snack"),
        ("Malpua", "Flour, Sugar Syrup, Fennel", 450, 6, 60, 18, "Snack"),
        ("Rogan Josh", "Lamb, Spices, Yogurt", 500, 30, 10, 25, "Dinner"),
        ("Tawa Paneer", "Paneer, Spices, Onion", 350, 15, 15, 20, "Dinner"),
        ("Makai Roti", "Maize Flour, Spices", 250, 5, 40, 6, "Lunch"),
        ("Mooli Paratha", "Radish, Wheat Flour, Spices", 300, 6, 45, 8, "Breakfast"),
        ("Kachori", "Flour, Lentils, Spices", 350, 7, 40, 15, "Snack"),
        ("Moong Dal Halwa", "Moong Dal, Ghee, Sugar", 450, 8, 50, 18, "Snack"),
        ("Besan Barfi", "Gram Flour, Sugar, Ghee", 400, 6, 55, 15, "Snack"),
        ("Batla Ki Sabzi", "Green Peas, Spices", 200, 6, 20, 8, "Side"),
        ("Panchmel Dal", "Five Lentils, Spices", 250, 10, 30, 6, "Lunch"),
        ("Khoya Jalebi", "Khoya, Flour, Sugar Syrup", 500, 5, 65, 20, "Snack"),
        ("Dal Pithi", "Lentils, Wheat Dumplings, Spices", 350, 12, 40, 10, "Lunch"),
        ("Sula", "Grilled Meat, Spices", 400, 28, 8, 18, "Dinner")
    ],
    "Maharastra": [
        ("Pav Bhaji", "Mixed Vegetables, Spices, Butter", 400, 8, 60, 12, "Dinner"),
        ("Vada Pav", "Potatoes, Gram Flour, Spices", 300, 6, 45, 10, "Snack"),
        ("Misal Pav", "Sprouts, Spices, Farsan", 350, 10, 50, 10, "Breakfast"),
        ("Puran Poli", "Wheat Flour, Jaggery, Lentils", 400, 8, 60, 12, "Snack"),
        ("Bharli Vangi", "Brinjal, Peanuts, Spices", 200, 4, 25, 8, "Side"),
        ("Kothimbir Vadi", "Gram Flour, Coriander, Spices", 150, 5, 20, 5, "Snack"),
        ("Modak", "Rice Flour, Coconut, Jaggery", 300, 4, 50, 8, "Snack"),
        ("Chicken Kolhapuri", "Chicken, Spices, Coconut", 400, 25, 10, 20, "Dinner"),
        ("Sabudana Vada", "Sago, Peanuts, Spices", 250, 5, 35, 8, "Snack"),
        ("Prawn Masala", "Prawns, Spices, Coconut", 350, 22, 10, 20, "Dinner"),
        ("Thalipeeth", "Multigrain Flour, Spices", 250, 6, 35, 7, "Breakfast"),
        ("Zunka", "Gram Flour, Onion, Spices", 200, 5, 20, 8, "Side"),
        ("Pitla", "Gram Flour, Garlic, Spices", 200, 4, 15, 6, "Lunch"),
        ("Bhakri", "Jowar Flour, Water, Salt", 180, 3, 30, 2, "Lunch"),
        ("Sol Kadhi", "Kokum, Coconut Milk", 100, 2, 10, 3, "Side"),
        ("Sheera", "Semolina, Ghee, Sugar", 350, 5, 50, 12, "Snack"),
        ("Shengdana Chutney", "Peanuts, Garlic, Spices", 120, 4, 5, 8, "Side"),
        ("Batata Bhaji", "Potatoes, Mustard Seeds, Spices", 250, 3, 30, 10, "Side"),
        ("Tambda Rassa", "Mutton, Red Curry, Spices", 450, 28, 10, 25, "Dinner"),
        ("Pandhra Rassa", "Chicken/Mutton, Coconut Milk, Spices", 400, 25, 10, 18, "Dinner"),
        ("Poha", "Flattened Rice, Peanuts, Mustard", 200, 4, 35, 5, "Breakfast"),
        ("Kharvas", "Colostrum Milk, Cardamom, Sugar", 250, 8, 25, 10, "Snack"),
        ("Alu Vadi", "Colocasia Leaves, Gram Flour", 220, 5, 30, 6, "Snack"),
        ("Danyachi Usal", "Peanuts, Coconut, Spices", 250, 6, 20, 10, "Side"),
        ("Ghavane", "Rice Flour, Water", 150, 3, 30, 2, "Breakfast"),
        ("Amboli", "Rice, Urad Dal, Fermented", 200, 4, 35, 4, "Breakfast"),
        ("Kolambi Bhaat", "Rice, Prawns, Spices", 400, 20, 50, 15, "Lunch"),
        ("Chakli", "Rice Flour, Gram Flour, Spices", 300, 5, 40, 15, "Snack"),
        ("Basundi", "Milk, Sugar, Cardamom", 350, 7, 45, 12, "Snack"),
        ("Ukadiche Modak", "Rice Flour, Coconut, Jaggery", 280, 4, 50, 6, "Snack")
    ],
    "Manipur": [
        ("Eromba", "Vegetables, Fermented Fish, Chillies", 150, 5, 15, 5, "Side"),
        ("Chak-hao Kheer", "Black Rice, Milk, Sugar", 400, 6, 60, 12, "Snack"),
        ("Kangshoi", "Vegetables, Spices, Ginger", 100, 3, 15, 2, "Side"),
        ("Singju", "Vegetables, Fermented Fish, Chillies", 150, 4, 15, 5, "Side"),
        ("Chicken Curry", "Chicken, Spices, Bamboo Shoot", 350, 25, 10, 20, "Dinner"),
        ("Fish Stew", "Fish, Spices, Herbs", 300, 20, 10, 15, "Dinner"),
        ("Pork with Bamboo", "Pork, Bamboo Shoot, Chillies", 400, 25, 5, 30, "Dinner"),
        ("Iromba", "Potatoes, Fermented Fish, Chillies", 150, 4, 20, 5, "Side"),
        ("Ngari", "Fermented Fish, Chillies", 50, 5, 0, 2, "Side"),
        ("Thongba", "Fish, Spices, Ginger", 250, 18, 10, 12, "Dinner"),
        ("Chamthong", "Vegetables, Ginger, Garlic, Spices", 120, 3, 18, 3, "Side"),
        ("Ooti", "Green Gram, Baking Soda, Spices", 200, 7, 30, 4, "Breakfast"),
        ("Aloo Kangmet", "Mashed Potatoes, Mustard Oil, Chillies", 180, 3, 25, 6, "Side"),
        ("Nga Thongba", "Fish, Spices, Tomatoes", 280, 20, 10, 12, "Dinner"),
        ("Paknam", "Besan, Banana Leaves, Herbs", 220, 6, 25, 8, "Snack"),
        ("Yongchak Iromba", "Tree Beans, Fermented Fish, Chillies", 160, 5, 20, 5, "Side"),
        ("U-Morok Chutney", "King Chilli, Fermented Fish", 60, 2, 5, 2, "Side"),
        ("Nga Atoiba Thongba", "Shredded Fish, Spices, Peas", 260, 18, 10, 10, "Dinner"),
        ("Morok Metpa", "Chillies, Ngari, Mustard Oil", 70, 2, 4, 3, "Side"),
        ("Kelli Chana", "Spiced Chickpeas, Herbs", 150, 6, 20, 4, "Snack"),
        ("Chak-Hao Amubi", "Black Rice, Coconut, Jaggery", 350, 5, 55, 10, "Snack"),
        ("Yendem Erongba", "Taro Root, Fermented Fish, Spices", 200, 6, 25, 5, "Side"),
        ("Bora", "Gram Flour, Vegetables, Oil", 300, 4, 30, 15, "Snack"),
        ("Laphu Thongba", "Banana Stem, Spices, Mustard", 180, 4, 20, 4, "Side"),
        ("Nga Ataoba", "Fried Fish, Spices", 280, 20, 8, 10, "Dinner"),
        ("Pork Thongba", "Pork, Spices, Bamboo Shoots", 400, 26, 5, 28, "Dinner"),
        ("Utan", "Yardlong Beans, Fermented Fish, Mustard Oil", 150, 4, 18, 5, "Side"),
        ("Kanghou", "Stir-Fried Vegetables, Spices", 180, 5, 20, 6, "Side"),
        ("Athongba", "Spiced Boiled Eggs, Masala", 250, 12, 10, 15, "Dinner")
    ],
    "Meghalaya": [
        ("Jadoh", "Rice, Pork, Spices", 400, 20, 50, 15, "Lunch"),
        ("Dohneiiong", "Pork, Black Sesame, Spices", 450, 25, 5, 30, "Dinner"),
        ("Nakham Bitchi", "Dried Fish, Chillies, Spices", 100, 8, 5, 5, "Side"),
        ("Pumaloi", "Rice Flour, Spices", 200, 4, 35, 3, "Breakfast"),
        ("Tungrymbai", "Fermented Soybeans, Spices", 150, 8, 15, 5, "Side"),
        ("Chicken with Bamboo", "Chicken, Bamboo Shoot, Spices", 350, 22, 10, 20, "Dinner"),
        ("Pork with Bamboo", "Pork, Bamboo Shoot, Chillies", 400, 25, 5, 30, "Dinner"),
        ("Fish Fry", "Fish, Spices, Oil", 300, 20, 5, 15, "Dinner"),
        ("Kyat", "Rice, Fermented Yeast", 150, 2, 30, 0, "Snack"),
        ("Pukhlein", "Rice Flour, Jaggery", 300, 4, 50, 8, "Snack"),
        ("Minil Songa", "Sticky Rice, Bamboo Leaves", 250, 4, 50, 3, "Snack"),
        ("Doh Khleh", "Boiled Pork, Onions, Spices", 300, 18, 10, 15, "Side"),
        ("Tit Tung", "Bamboo Shoot, Pork, Spices", 350, 20, 10, 20, "Dinner"),
        ("Doh Jem", "Minced Pork, Spices", 320, 18, 5, 20, "Lunch"),
        ("Ja Stem", "Rice, Mustard Greens, Spices", 200, 5, 40, 5, "Lunch"),
        ("Black Sesame Chutney", "Black Sesame Seeds, Chillies", 100, 3, 5, 7, "Side"),
        ("Rymbai", "Soybeans, Mustard Oil, Spices", 180, 9, 20, 6, "Side"),
        ("Jhur Sideh", "Dry Fish, Banana Flower, Spices", 220, 12, 10, 8, "Side"),
        ("Sweet Rice Pudding", "Rice, Milk, Sugar, Cardamom", 350, 6, 55, 10, "Snack"),
        ("Sakin Gata", "Sticky Rice, Coconut, Jaggery", 300, 5, 50, 8, "Snack"),
        ("Pork Intestine Fry", "Pork Intestine, Spices", 400, 22, 5, 30, "Dinner"),
        ("Spicy Chicken Gravy", "Chicken, Spices, Onion", 350, 24, 8, 18, "Dinner"),
        ("Mashed Potato Chutney", "Potatoes, Mustard Oil, Chillies", 150, 3, 20, 5, "Side"),
        ("Steamed Pork Balls", "Pork, Herbs, Spices", 300, 20, 5, 15, "Snack"),
        ("Red Rice with Gravy", "Red Rice, Spiced Broth", 280, 5, 45, 6, "Lunch"),
        ("Fried Yam", "Yam, Oil, Spices", 200, 2, 30, 8, "Snack"),
        ("Herb Pork Curry", "Pork, Local Herbs, Spices", 380, 24, 10, 25, "Dinner"),
        ("Crushed Soybean Chutney", "Soybean, Spices, Mustard Oil", 160, 6, 10, 7, "Side"),
        ("Ja Doh Snam", "Rice, Pig Blood, Spices", 400, 22, 45, 20, "Lunch"),
        ("Pumpkin Flower Pakoras", "Pumpkin Flower, Gram Flour, Spices", 250, 5, 20, 10, "Snack")
    ],
    "Mizoram": [
        ("Bai", "Vegetables, Pork, Spices", 300, 15, 20, 15, "Lunch"),
        ("Vawksa Rep", "Pork, Spices, Ginger", 400, 25, 5, 30, "Dinner"),
        ("Misa Mach Poora", "Prawns, Spices, Banana Leaf", 250, 18, 5, 15, "Dinner"),
        ("Chhum Han", "Vegetables, Spices, Bamboo Shoot", 150, 3, 20, 3, "Side"),
        ("Koat Pitha", "Rice Flour, Banana, Jaggery", 300, 4, 50, 8, "Snack"),
        ("Fish Stew", "Fish, Spices, Herbs", 250, 18, 10, 12, "Dinner"),
        ("Chicken with Bamboo", "Chicken, Bamboo Shoot, Spices", 350, 22, 10, 20, "Dinner"),
        ("Pork with Bamboo", "Pork, Bamboo Shoot, Chillies", 400, 25, 5, 30, "Dinner"),
        ("Sawhchiar", "Rice, Chicken, Spices", 400, 20, 50, 15, "Lunch"),
        ("Mizo Dal", "Lentils, Spices, Ginger", 150, 6, 20, 3, "Side"),
        ("Bekang", "Fermented Soybeans, Spices", 100, 6, 10, 4, "Side"),
        ("Hnahkiah", "Boiled Pork, Spices, Onion", 350, 20, 10, 20, "Dinner"),
        ("Arsa Buhchiar", "Sticky Rice, Pork Fat, Spices", 450, 18, 55, 22, "Lunch"),
        ("Chhangban", "Sticky Rice Cake, Banana Leaf", 300, 4, 50, 6, "Snack"),
        ("Ruihin Salad", "Fish, Onion, Mustard Oil", 200, 12, 5, 10, "Side"),
        ("Tohbal", "Cabbage, Dry Fish, Chillies", 180, 6, 20, 8, "Side"),
        ("Rawtuai", "Boiled Vegetables, Salt", 120, 2, 15, 2, "Side"),
        ("Pukhlen", "Sticky Rice, Jaggery", 280, 4, 50, 5, "Snack"),
        ("Dal Kan", "Lentils, Tomato, Spices", 160, 6, 20, 3, "Side"),
        ("Sa Rep", "Fried Pork, Spices", 350, 22, 5, 25, "Dinner"),
        ("Panch Phoran Tarkari", "Mixed Vegetables, Spices", 200, 5, 30, 6, "Lunch"),
        ("Zawngtah", "Smoked Beef, Local Spices", 400, 26, 10, 22, "Dinner"),
        ("Awmla Thir", "Gooseberry, Salt, Spices", 100, 1, 10, 1, "Snack"),
        ("Khamrang", "Spicy Dry Pork, Herbs", 380, 24, 5, 28, "Dinner"),
        ("Tungtap", "Fermented Fish Paste, Chillies", 120, 10, 2, 5, "Side"),
        ("Bekang Curry", "Soybean, Potato, Spices", 250, 8, 30, 10, "Side"),
        ("Chingal", "Mustard Leaves, Rice Powder", 180, 4, 25, 5, "Side"),
        ("Thlensong", "Bamboo Shoot, Dry Fish, Spices", 220, 10, 15, 7, "Side"),
        ("Kawrtheng", "Chicken Blood Curry, Spices", 350, 20, 5, 18, "Dinner"),
        ("Buhchiar", "Rice, Pork Broth, Spices", 400, 20, 45, 12, "Lunch")
    ],
    "Nagaland": [
        ("Pork with Bamboo", "Pork, Bamboo Shoot, Chillies", 400, 25, 5, 30, "Dinner"),
        ("Axone", "Fermented Soybeans, Spices", 150, 8, 15, 5, "Side"),
        ("Smoked Pork", "Pork, Spices, Smoke", 450, 28, 5, 30, "Dinner"),
        ("Fish in Bamboo", "Fish, Spices, Bamboo Shoot", 300, 20, 5, 15, "Dinner"),
        ("Chicken with Anishi", "Chicken, Fermented Yam Leaves, Spices", 350, 22, 10, 20, "Dinner"),
        ("Galho", "Rice, Vegetables, Spices", 200, 4, 35, 5, "Lunch"),
        ("Naga King Chilli Chutney", "King Chilli, Garlic, Spices", 50, 1, 5, 2, "Side"),
        ("Pork with Dry Bamboo", "Pork, Dry Bamboo Shoot, Spices", 400, 25, 5, 30, "Dinner"),
        ("Zutho", "Rice, Fermented Yeast", 150, 2, 30, 0, "Snack"),
        ("Vegetable Stew", "Mixed Vegetables, Spices", 150, 3, 20, 3, "Side"),
        ("Beef with Bamboo Shoot", "Beef, Bamboo Shoot, Spices", 400, 26, 5, 28, "Dinner"),
        ("Roasted Axone Pork", "Pork, Fermented Soybean, Spices", 420, 24, 10, 30, "Dinner"),
        ("Dry River Fish", "Small Fish, Spices, Oil", 250, 18, 5, 12, "Side"),
        ("Anishi with Smoked Meat", "Yam Leaf Cakes, Smoked Meat", 370, 20, 10, 25, "Dinner"),
        ("Black Sticky Rice Pudding", "Black Rice, Coconut, Sugar", 300, 5, 45, 8, "Snack"),
        ("Pumpkin Stew", "Pumpkin, Garlic, Spices", 180, 3, 30, 4, "Side"),
        ("Naga Chicken Curry", "Chicken, Potato, Local Spices", 350, 22, 10, 18, "Dinner"),
        ("Taro with Bamboo Shoot", "Taro Root, Bamboo Shoot, Spices", 220, 6, 30, 6, "Side"),
        ("Snail Curry", "Snails, Bamboo Shoot, Spices", 200, 14, 5, 10, "Dinner"),
        ("Silkworm Fry", "Silkworm Larvae, Spices, Oil", 300, 20, 5, 18, "Snack"),
        ("Local Beans Stew", "Beans, Tomato, Spices", 180, 7, 20, 4, "Side"),
        ("Crab Chutney", "River Crab, Spices", 220, 15, 5, 10, "Side"),
        ("Sticky Rice Balls", "Sticky Rice, Salt", 250, 4, 55, 2, "Snack"),
        ("Fermented Bamboo Soup", "Fermented Bamboo, Spices", 150, 2, 25, 3, "Side"),
        ("Sweet Potato Stew", "Sweet Potato, Garlic, Spices", 200, 3, 40, 2, "Side"),
        ("Dried Pork Curry", "Dried Pork, Tomato, Spices", 380, 24, 8, 22, "Dinner"),
        ("Chutney of Perilla Seeds", "Perilla Seeds, Chili, Garlic", 120, 6, 5, 7, "Side"),
        ("Millet Porridge", "Millet, Water, Salt", 180, 5, 35, 3, "Breakfast"),
        ("Dry Beef with Ginger", "Beef, Ginger, Garlic", 370, 25, 5, 22, "Dinner"),
        ("Jackfruit Seeds Stew", "Jackfruit Seeds, Spices", 200, 4, 30, 5, "Side")
    ],
    "Odisha": [
        ("Pakhala Bhata", "Fermented Rice, Water, Spices", 200, 4, 35, 3, "Lunch"),
        ("Dalma", "Lentils, Mixed Vegetables, Spices", 250, 8, 40, 5, "Lunch"),
        ("Chhencheda", "Fish, Spices, Tamarind", 300, 20, 10, 15, "Dinner"),
        ("Rasabali", "Milk, Sugar, Spices", 400, 8, 50, 15, "Snack"),
        ("Chhena Poda", "Cheese, Sugar, Cardamom", 450, 10, 60, 15, "Snack"),
        ("Pitha", "Rice Flour, Jaggery, Coconut", 300, 4, 50, 8, "Snack"),
        ("Mutton Jholo", "Mutton, Spices, Onions", 400, 28, 10, 25, "Dinner"),
        ("Crab Curry", "Crab, Spices, Coconut", 350, 22, 10, 20, "Dinner"),
        ("Badi Chura", "Sun-Dried Lentil Dumplings, Spices", 150, 6, 20, 3, "Side"),
        ("Khicede", "Rice, Lentils, Spices", 250, 8, 40, 5, "Lunch"),
        ("Santula", "Boiled Vegetables, Spices", 180, 4, 25, 3, "Side"),
        ("Kanika", "Sweetened Rice, Dry Fruits", 300, 6, 50, 8, "Lunch"),
        ("Chhena Jhili", "Fresh Cheese, Sugar Syrup", 400, 8, 55, 15, "Snack"),
        ("Macha Besara", "Fish, Mustard Paste, Spices", 350, 20, 10, 18, "Dinner"),
        ("Ghugni", "Yellow Peas, Onion, Spices", 250, 6, 35, 6, "Snack"),
        ("Besara", "Vegetables, Mustard Sauce", 200, 5, 30, 5, "Side"),
        ("Poda Pitha", "Rice Flour, Jaggery, Coconut", 320, 5, 55, 10, "Snack"),
        ("Chakuli Pitha", "Rice, Black Gram, Ghee", 300, 6, 50, 8, "Breakfast"),
        ("Manda Pitha", "Rice Flour, Coconut, Jaggery", 280, 4, 45, 7, "Snack"),
        ("Jhili", "Deep-fried Wheat Flour, Sugar Syrup", 400, 4, 60, 12, "Snack"),
        ("Chhatu Rai", "Mushrooms, Mustard Paste", 200, 5, 25, 5, "Side"),
        ("Kadali Manja Rai", "Banana Stem, Mustard Sauce", 180, 4, 20, 4, "Side"),
        ("Besi Jholo", "Lentils, Tomato, Spices", 220, 7, 30, 4, "Lunch"),
        ("Macha Tarkari", "Fish, Potato, Spices", 320, 18, 15, 12, "Dinner"),
        ("Janhi Aloo Posto", "Ridge Gourd, Potato, Poppy Seeds", 200, 5, 25, 4, "Side"),
        ("Alu Potala Rasa", "Potato, Pointed Gourd, Gravy", 250, 6, 30, 6, "Lunch"),
        ("Rasi Jholo", "Black Sesame, Vegetables, Spices", 220, 4, 20, 8, "Side"),
        ("Pani Kakharu Bhaja", "Pumpkin, Spices, Oil", 180, 3, 20, 5, "Side"),
        ("Sijha Manda", "Steamed Rice Dumpling, Coconut", 280, 4, 50, 7, "Snack"),
        ("Chhena Gaja", "Cheese, Sugar, Cardamom", 420, 10, 55, 16, "Snack")
    ],
    "Punjab": [
        ("Makki Di Roti", "Corn Flour, Spices", 200, 5, 35, 5, "Lunch"),
        ("Sarson Da Saag", "Mustard Greens, Spinach, Spices", 150, 5, 15, 8, "Lunch"),  # Using seasonal mustard greens
        ("Butter Chicken", "Chicken, Butter, Cream, Spices", 500, 30, 20, 30, "Dinner"),
        ("Amritsari Kulcha", "Wheat Flour, Potatoes, Spices", 300, 8, 45, 8, "Breakfast"),
        ("Chole Bhature", "Chickpeas, Wheat Flour, Spices", 450, 12, 60, 15, "Lunch"),
        ("Lassi", "Yogurt, Sugar, Water", 200, 6, 30, 5, "Snack"),
        ("Tandoori Chicken", "Chicken, Yogurt, Spices", 400, 28, 5, 25, "Dinner"),
        ("Pinni", "Wheat Flour, Jaggery, Ghee", 500, 6, 70, 20, "Snack"),
        ("Aloo Paratha", "Wheat Flour, Potatoes, Spices", 350, 8, 50, 10, "Breakfast"),
        ("Gajar Ka Halwa", "Carrots, Milk, Sugar, Ghee", 500, 8, 60, 20, "Snack"), # Using seasonal carrots
        ("Paneer Tikka", "Paneer, Yogurt, Spices", 350, 18, 10, 20, "Snack"),
        ("Rajma Chawal", "Kidney Beans, Rice, Spices", 400, 12, 55, 10, "Lunch"),
        ("Kadhi Pakora", "Gram Flour, Yogurt, Spices", 300, 10, 25, 15, "Lunch"),
        ("Baingan Bharta", "Brinjal, Onion, Spices", 250, 5, 20, 12, "Side"),
        ("Bhindi Masala", "Ladyfinger, Onion, Spices", 200, 4, 15, 10, "Side"),
        ("Shakkar Para", "Wheat Flour, Sugar, Ghee", 300, 4, 50, 15, "Snack"),
        ("Methi Paratha", "Wheat Flour, Fenugreek, Spices", 300, 7, 45, 8, "Breakfast"),
        ("Kesar Phirni", "Rice, Milk, Sugar, Saffron", 350, 6, 50, 12, "Snack"),
        ("Jeera Aloo", "Potato, Cumin, Spices", 250, 3, 30, 10, "Side"),
        ("Besan Ladoo", "Gram Flour, Sugar, Ghee", 450, 6, 60, 20, "Snack"),
        ("Gobhi Paratha", "Wheat Flour, Cauliflower, Spices", 350, 8, 50, 10, "Breakfast"),
        ("Moong Dal Halwa", "Moong Dal, Ghee, Sugar", 500, 10, 55, 25, "Snack"),
        ("Chana Masala", "Chickpeas, Spices, Tomato", 350, 12, 40, 10, "Lunch"),
        ("Punjabi Pakora", "Gram Flour, Vegetables, Spices", 300, 6, 25, 15, "Snack"),
        ("Stuffed Capsicum", "Bell Peppers, Potatoes, Spices", 300, 6, 25, 12, "Side"),
        ("Dahi Bhalla", "Lentil Dumplings, Yogurt, Chutney", 350, 10, 40, 12, "Snack"),
        ("Punjabi Kheer", "Rice, Milk, Sugar, Dry Fruits", 400, 8, 50, 15, "Snack"),
        ("Tandoori Roti", "Wheat Flour, Ghee", 200, 4, 30, 5, "Lunch"),
        ("Achari Paneer", "Paneer, Pickle Spices, Onion", 350, 16, 10, 20, "Dinner")
    ],
    "Rajasthan": [
        ("Dal Baati Churma", "Wheat Flour, Lentils, Ghee", 500, 12, 70, 15, "Lunch"),
        ("Laal Maas", "Mutton, Red Chillies, Spices", 450, 30, 10, 30, "Dinner"),
        ("Gatte Ki Sabzi", "Gram Flour, Spices, Yogurt", 200, 8, 25, 8, "Lunch"),
        ("Ker Sangri", "Dried Berries, Beans, Spices", 150, 4, 20, 5, "Side"),
        ("Bajre Ki Roti", "Pearl Millet, Spices", 200, 5, 35, 5, "Lunch"),
        ("Mohanthal", "Gram Flour, Sugar, Ghee", 500, 6, 70, 20, "Snack"),
        ("Pyaaz Kachori", "Wheat Flour, Onions, Spices", 300, 6, 45, 10, "Snack"),
        ("Mirchi Bada", "Green Chillies, Gram Flour, Spices", 150, 3, 20, 5, "Snack"),
        ("Rabdi", "Milk, Sugar, Nuts", 400, 8, 50, 15, "Snack"),
        ("Ghevar", "Wheat Flour, Sugar Syrup, Ghee", 450, 6, 60, 20, "Snack"),
        ("Mawa Kachori", "Maida, Mawa, Sugar Syrup", 400, 6, 50, 15, "Snack"),
        ("Papad Ki Sabzi", "Papad, Yogurt, Spices", 200, 5, 20, 8, "Side"),
        ("Bajra Khichdi", "Pearl Millet, Lentils, Spices", 300, 10, 40, 5, "Lunch"),
        ("Churma Ladoo", "Wheat Flour, Jaggery, Ghee", 450, 6, 60, 20, "Snack"),
        ("Safed Maas", "Mutton, Curd, Cashew Paste", 450, 28, 10, 25, "Dinner"),
        ("Kachri Ki Sabzi", "Kachri, Spices, Oil", 200, 4, 15, 10, "Side"),
        ("Methi Bajra Poori", "Fenugreek, Pearl Millet, Spices", 250, 6, 30, 10, "Snack"),
        ("Besan Chilla", "Gram Flour, Spices, Onion", 200, 8, 20, 5, "Breakfast"),
        ("Malpua", "Maida, Sugar Syrup, Ghee", 400, 4, 60, 18, "Snack"),
        ("Raj Kachori", "Maida, Chutney, Curd, Stuffing", 450, 8, 60, 15, "Snack"),
        ("Kadhi", "Besan, Yogurt, Spices", 200, 6, 25, 8, "Lunch"),
        ("Aloo Pyaaz Ki Sabzi", "Potato, Onion, Spices", 250, 5, 30, 10, "Side"),
        ("Gond Ke Ladoo", "Edible Gum, Wheat Flour, Ghee", 500, 6, 60, 25, "Snack"),
        ("Moong Dal Halwa", "Moong Dal, Ghee, Sugar", 500, 10, 55, 25, "Snack"),
        ("Khoba Roti", "Wheat Flour, Ghee, Spices", 300, 6, 40, 12, "Lunch"),
        ("Methi Thepla", "Fenugreek, Wheat Flour, Spices", 250, 6, 35, 8, "Breakfast"),
        ("Til Ke Ladoo", "Sesame Seeds, Jaggery", 350, 4, 40, 15, "Snack"),
        ("Sev Tamatar", "Tomato, Sev, Spices", 250, 6, 30, 8, "Lunch"),
        ("Aate Ka Halwa", "Wheat Flour, Ghee, Sugar", 400, 6, 50, 20, "Snack")
    ],
    "Sikkim": [
        ("Momo", "Wheat Flour, Pork, Spices", 300, 15, 40, 10, "Snack"),
        ("Thukpa", "Noodles, Vegetables, Spices", 250, 8, 40, 5, "Lunch"),
        ("Gundruk", "Fermented Greens, Spices", 100, 3, 15, 2, "Side"),
        ("Sael Roti", "Rice Flour, Spices, Oil", 200, 4, 35, 5, "Breakfast"),
        ("Phagshapa", "Pork, Radish, Spices", 400, 25, 10, 25, "Dinner"),
        ("Chhurpi Soup", "Chhurpi Cheese, Spices", 150, 6, 15, 5, "Side"),
        ("Chicken Thukpa", "Noodles, Chicken, Spices", 300, 15, 40, 10, "Lunch"),
        ("Sha Phaley", "Wheat Flour, Meat, Spices", 350, 15, 45, 12, "Snack"),
        ("Sinki Soup", "Fermented Radish, Spices", 100, 3, 15, 2, "Side"),
        ("Chang", "Millet, Fermented Yeast", 150, 2, 30, 0, "Snack"),
        ("Kinema Curry", "Fermented Soybeans, Spices", 200, 8, 20, 5, "Side"),
        ("Chhurpi with Spinach", "Chhurpi Cheese, Spinach, Spices", 200, 7, 15, 8, "Side"),
        ("Buckwheat Roti", "Buckwheat, Spices", 180, 5, 30, 3, "Breakfast"),
        ("Fried Momo", "Wheat Flour, Pork, Spices, Oil", 350, 18, 40, 15, "Snack"),
        ("Gyathuk", "Noodles, Vegetables, Broth", 250, 7, 35, 4, "Lunch"),
        ("Dry Meat Curry", "Dried Meat, Spices", 350, 22, 10, 20, "Dinner"),
        ("Zimbu Curry", "Herbs, Yak Cheese, Spices", 300, 10, 20, 12, "Dinner"),
        ("Fing (Glass Noodle Salad)", "Glass Noodles, Vegetables, Spices", 200, 5, 35, 4, "Side"),
        ("Thenthuk", "Pulled Noodles, Vegetables, Spices", 300, 10, 40, 5, "Lunch"),
        ("Bamboo Shoot Curry", "Bamboo Shoot, Spices", 150, 4, 20, 4, "Side"),
        ("Millet Pancakes", "Millet Flour, Jaggery", 250, 5, 35, 6, "Breakfast"),
        ("Beaten Rice with Yogurt", "Flattened Rice, Yogurt, Sugar", 200, 4, 30, 3, "Breakfast"),
        ("Fried Chhurpi", "Chhurpi Cheese, Oil", 180, 6, 5, 12, "Snack"),
        ("Yak Butter Tea", "Tea, Yak Butter, Salt", 100, 1, 2, 8, "Snack"),
        ("Jhol Momo", "Momo, Spicy Broth", 350, 16, 45, 12, "Lunch"),
        ("Shimi Ko Achar", "String Beans, Mustard Oil, Spices", 120, 3, 10, 6, "Side"),
        ("Aloo Dum", "Potatoes, Spices, Tomatoes", 250, 4, 30, 10, "Side"),
        ("Fermented Spinach Curry", "Fermented Spinach, Spices", 180, 4, 15, 6, "Side"),
        ("Kodo Ko Roti", "Finger Millet, Spices", 200, 5, 30, 5, "Breakfast"),
        ("Steamed Veggies with Chilli Sauce", "Seasonal Vegetables, Chilli Paste", 150, 3, 10, 6, "Side")
    ],
    "Tamil Nadu": [
        ("Dosa", "Rice, Urad Dal, Fenugreek Seeds, Salt", 200, 6, 30, 5, "Breakfast"),
        ("Idli", "Rice, Urad Dal, Fenugreek Seeds, Salt", 150, 5, 25, 3, "Breakfast"),
        ("Sambar", "Toor Dal, Tamarind, Tomatoes, Drumsticks, Turmeric, Coriander", 150, 6, 20, 3, "Side"),
        ("Rasam", "Tomatoes, Tamarind, Black Pepper, Cumin, Garlic", 100, 2, 15, 2, "Side"),
        ("Pongal", "Rice, Moong Dal, Black Pepper, Cumin, Ghee", 250, 8, 40, 6, "Breakfast"),
        ("Chicken Chettinad", "Chicken, Coconut, Fennel Seeds, Star Anise, Red Chillies", 400, 25, 10, 20, "Dinner"),
        ("Vada", "Urad Dal, Black Pepper, Curry Leaves, Oil", 200, 6, 25, 8, "Snack"),
        ("Mango Pachadi", "Raw Mango, Jaggery, Red Chillies, Mustard Seeds", 150, 2, 30, 3, "Side"),  # Using seasonal mango
        ("Fish Kuzhambu", "Fish, Tamarind, Shallots, Red Chillies, Fenugreek", 300, 20, 10, 15, "Dinner"),
        ("Kothu Parotta", "Wheat Flour, Onions, Tomatoes, Green Chillies, Eggs", 350, 10, 50, 10, "Dinner"),
        ("Kuzhi Paniyaram", "Rice, Urad Dal, Mustard Seeds, Curry Leaves", 200, 5, 30, 5, "Breakfast"),
        ("Thayir Sadam", "Rice, Curd, Mustard Seeds, Curry Leaves", 250, 6, 35, 8, "Lunch"),
        ("Kara Kuzhambu", "Tamarind, Shallots, Garlic, Red Chillies", 200, 4, 20, 10, "Side"),
        ("Paruppu Usili", "Toor Dal, Vegetables, Curry Leaves", 250, 10, 20, 8, "Side"),
        ("Puli Sadam", "Rice, Tamarind, Mustard, Red Chillies", 300, 6, 40, 10, "Lunch"),
        ("Thengai Sadam", "Rice, Coconut, Mustard Seeds", 250, 4, 35, 8, "Lunch"),
        ("Lemon Rice", "Rice, Lemon, Mustard Seeds, Curry Leaves", 250, 4, 35, 6, "Lunch"),
        ("Aviyal", "Mixed Vegetables, Coconut, Curd, Curry Leaves", 200, 5, 20, 8, "Side"),
        ("Murukku", "Rice Flour, Urad Dal, Cumin, Oil", 300, 5, 40, 15, "Snack"),
        ("Adai", "Rice, Lentils, Curry Leaves, Red Chillies", 250, 10, 30, 8, "Breakfast"),
        ("Appam", "Rice, Coconut Milk, Yeast", 200, 4, 35, 4, "Breakfast"),
        ("Vegetable Kurma", "Mixed Vegetables, Coconut, Spices", 250, 6, 20, 10, "Dinner"),
        ("Ragi Kali", "Finger Millet, Water, Salt", 200, 3, 30, 2, "Lunch"),
        ("Sundal", "Chickpeas, Coconut, Mustard Seeds", 200, 7, 25, 5, "Snack"),
        ("Bisi Bele Bath", "Rice, Toor Dal, Vegetables, Tamarind", 300, 8, 40, 10, "Lunch"),
        ("Paal Payasam", "Rice, Milk, Sugar, Cardamom", 400, 6, 60, 10, "Snack"),
        ("Sweet Pongal", "Rice, Jaggery, Ghee, Cashews", 350, 6, 50, 12, "Snack"),
        ("Meen Varuval", "Fish, Spices, Oil", 300, 20, 5, 15, "Dinner"),
        ("Poriyal", "Vegetables, Mustard Seeds, Coconut", 150, 4, 15, 5, "Side"),
        ("Kootu", "Lentils, Vegetables, Coconut", 200, 6, 20, 6, "Side")
    ],
    "Telangana": [
        ("Hyderabadi Biryani", "Rice, Chicken, Spices, Saffron", 600, 25, 80, 20, "Lunch"),
        ("Pachi Pulusu", "Tamarind, Onions, Spices", 100, 2, 15, 2, "Side"),
        ("Sakinalu", "Rice Flour, Sesame Seeds, Spices", 200, 4, 30, 5, "Snack"),
        ("Garelu", "Urad Dal, Spices, Oil", 200, 6, 25, 8, "Snack"),
        ("Qubani Ka Meetha", "Apricots, Sugar, Nuts", 400, 4, 60, 12, "Snack"),
        ("Pappu Charu", "Lentils, Tamarind, Spices", 150, 6, 20, 3, "Side"),
        ("Chicken 65", "Chicken, Spices, Yogurt", 350, 25, 10, 20, "Dinner"),
        ("Pesarattu", "Green Gram, Rice, Spices", 200, 8, 30, 5, "Breakfast"),
        ("Mutton Curry", "Mutton, Spices, Onions", 400, 28, 10, 25, "Dinner"),
        ("Jonna Rotte", "Sorghum Flour, Spices", 200, 5, 35, 5, "Breakfast"),
        ("Hyderabadi Haleem", "Wheat, Meat, Ghee, Lentils", 500, 28, 60, 20, "Dinner"),
        ("Kodi Pulusu", "Chicken, Tamarind, Onions, Spices", 350, 25, 10, 15, "Dinner"),
        ("Natu Kodi Curry", "Country Chicken, Spices", 400, 30, 5, 20, "Dinner"),
        ("Bagara Baingan", "Brinjal, Peanuts, Sesame, Spices", 250, 6, 20, 15, "Side"),
        ("Mirchi Ka Salan", "Green Chillies, Peanuts, Tamarind", 200, 4, 15, 12, "Side"),
        ("Boti Curry", "Goat Intestines, Spices", 350, 20, 5, 25, "Dinner"),
        ("Kakarakaya Fry", "Bitter Gourd, Spices, Onions", 200, 3, 10, 15, "Side"),
        ("Kura", "Mixed Vegetables, Spices", 250, 6, 25, 10, "Side"),
        ("Ragi Sangati", "Finger Millet, Rice, Ghee", 250, 4, 35, 5, "Lunch"),
        ("Uggani", "Puffed Rice, Onions, Green Chillies", 150, 3, 25, 4, "Breakfast"),
        ("Vankaya Pappu", "Brinjal, Toor Dal, Spices", 200, 6, 20, 6, "Lunch"),
        ("Mokkajonna Garelu", "Corn, Urad Dal, Spices", 250, 8, 30, 8, "Snack"),
        ("Nuvvula Undalu", "Sesame Seeds, Jaggery", 200, 4, 30, 8, "Snack"),
        ("Bobbatlu", "Chana Dal, Jaggery, Flour", 300, 6, 50, 10, "Snack"),
        ("Telangana Fish Curry", "Fish, Tamarind, Spices", 300, 20, 5, 15, "Dinner"),
        ("Minapa Roti", "Urad Dal, Spices", 250, 8, 30, 6, "Breakfast"),
        ("Gongura Mutton", "Gongura Leaves, Mutton, Spices", 400, 28, 5, 20, "Dinner"),
        ("Bendakaya Fry", "Okra, Onions, Spices", 200, 4, 15, 10, "Side"),
        ("Rava Dosa", "Semolina, Rice Flour, Spices", 200, 5, 35, 6, "Breakfast"),
        ("Masala Garelu", "Urad Dal, Onions, Green Chillies", 250, 8, 30, 10, "Snack")
    ],
    "Tripura": [
        ("Mui Borok", "Vegetables, Bamboo Shoot, Spices", 150, 3, 20, 3, "Side"),
        ("Awan Bangwi", "Rice, Vegetables, Spices", 200, 4, 35, 5, "Lunch"),
        ("Pork with Bamboo", "Pork, Bamboo Shoot, Chillies", 400, 25, 5, 30, "Dinner"),
        ("Fish Stew", "Fish, Spices, Herbs", 300, 20, 10, 15, "Dinner"),
        ("Chicken Curry", "Chicken, Spices, Ginger", 350, 22, 10, 20, "Dinner"),
        ("Chakhwi", "Vegetables, Spices, Bamboo Shoot", 150, 3, 20, 3, "Side"),
        ("Mosdeng Serma", "Vegetables, Chillies, Spices", 100, 2, 15, 2, "Side"),
        ("Berma", "Fermented Fish, Chillies", 50, 5, 0, 2, "Side"),
        ("Wahan", "Pork, Spices, Ginger", 400, 25, 5, 30, "Dinner"),
        ("Gudok", "Vegetables, Spices, Fish", 200, 10, 20, 8, "Lunch"),
        ("Bangui Rice Cake", "Sticky Rice, Spices, Banana Leaves", 250, 5, 50, 5, "Snack"),
        ("Bamboo Shoot Curry", "Bamboo Shoot, Spices, Lentils", 200, 6, 30, 5, "Lunch"),
        ("Tilapia Curry", "Tilapia, Spices, Tomatoes", 300, 22, 10, 12, "Dinner"),
        ("Sticky Rice with Pork", "Sticky Rice, Pork, Bamboo Leaves", 350, 20, 45, 12, "Dinner"),
        ("Bamboo Shoot Stir Fry", "Bamboo Shoot, Chillies, Onions", 150, 4, 15, 5, "Side"),
        ("Rice and Berma", "Rice, Fermented Fish, Spices", 250, 10, 35, 8, "Lunch"),
        ("Jackfruit Curry", "Raw Jackfruit, Spices, Mustard", 200, 4, 25, 5, "Side"),
        ("Sweet Rice", "Rice, Coconut, Jaggery", 300, 4, 55, 8, "Snack"),
        ("Banana Stem Curry", "Banana Stem, Spices, Tamarind", 150, 3, 20, 4, "Side"),
        ("Takhui", "Mixed Greens, Chillies, Mustard Oil", 120, 2, 10, 5, "Side"),
        ("Smoked Fish with Vegetables", "Smoked Fish, Greens, Spices", 250, 18, 10, 10, "Dinner"),
        ("Pumpkin Leaf Chutney", "Pumpkin Leaves, Mustard, Spices", 100, 2, 10, 3, "Side"),
        ("Khichuri", "Rice, Lentils, Vegetables", 250, 8, 35, 5, "Lunch"),
        ("Pancharatna Dal", "Mixed Lentils, Spices", 200, 12, 25, 3, "Lunch"),
        ("Chire Bhaja", "Flattened Rice, Spices, Peanuts", 180, 4, 30, 4, "Snack"),
        ("Jalpai Chutney", "Indian Olive, Sugar, Spices", 120, 1, 30, 1, "Side"),
        ("Chitol Macher Muitha", "Chitol Fish, Spices, Gravy", 350, 22, 10, 15, "Dinner"),
        ("Pumpkin Curry", "Pumpkin, Mustard Seeds, Spices", 180, 3, 20, 5, "Side"),
        ("Kolar Kofta", "Raw Banana, Spices, Gravy", 250, 5, 30, 8, "Lunch")
    ],
    "Uttar Pradesh": [
        ("Aloo Kachori", "Wheat Flour, Potatoes, Spices", 300, 6, 45, 10, "Snack"),
        ("Tunday Kebab", "Mutton, Spices, Yogurt", 450, 30, 5, 30, "Dinner"),
        ("Puri Sabzi", "Wheat Flour, Potatoes, Spices", 350, 8, 50, 10, "Breakfast"),
        ("Kheer", "Rice, Milk, Sugar, Nuts", 400, 8, 60, 12, "Snack"),
        ("Biryani", "Rice, Chicken, Spices", 600, 25, 80, 20, "Lunch"),
        ("Mathura Peda", "Milk Solids, Sugar, Ghee", 500, 8, 60, 20, "Snack"),
        ("Chaat", "Potatoes, Chickpeas, Spices", 200, 5, 30, 5, "Snack"),
        ("Shahi Tukda", "Bread, Milk, Sugar, Nuts", 450, 8, 60, 15, "Snack"),
        ("Mutton Korma", "Mutton, Yogurt, Spices", 400, 28, 10, 25, "Dinner"),
        ("Baingan Bharta", "Brinjal, Spices, Oil", 150, 3, 20, 5, "Side"),
        ("Litti Chokha", "Wheat Flour, Sattu, Brinjal, Spices", 400, 10, 50, 15, "Lunch"),
        ("Nimona", "Green Peas, Spices, Potatoes", 200, 6, 25, 5, "Lunch"),
        ("Kachri", "Wheat Flour, Spices, Ghee", 250, 5, 35, 10, "Snack"),
        ("Tehri", "Rice, Vegetables, Spices", 300, 6, 50, 8, "Lunch"),
        ("Malai Peda", "Condensed Milk, Sugar, Cardamom", 350, 6, 45, 12, "Snack"),
        ("Sheermal", "Maida, Milk, Saffron, Sugar", 300, 5, 40, 10, "Breakfast"),
        ("Kakori Kebab", "Minced Mutton, Spices, Ghee", 400, 28, 5, 25, "Dinner"),
        ("Bedmi Puri", "Wheat Flour, Urad Dal, Spices", 350, 10, 45, 10, "Breakfast"),
        ("Jalebi", "Refined Flour, Sugar Syrup", 300, 2, 60, 10, "Snack"),
        ("Imarti", "Urad Dal, Sugar, Ghee", 350, 5, 50, 12, "Snack"),
        ("Paneer Pasanda", "Paneer, Cream, Spices", 400, 15, 20, 25, "Dinner"),
        ("Dum Aloo", "Potatoes, Yogurt, Spices", 300, 6, 25, 15, "Dinner"),
        ("Chana Ghugni", "Black Chickpeas, Spices", 250, 10, 30, 6, "Snack"),
        ("Aloo Tamatar Curry", "Potatoes, Tomatoes, Spices", 200, 4, 20, 5, "Side"),
        ("Zarda Pulao", "Rice, Sugar, Dry Fruits, Saffron", 400, 5, 65, 12, "Snack"),
        ("Gajar Halwa", "Carrots, Milk, Sugar, Ghee", 450, 8, 60, 20, "Snack"),
        ("Palak Paneer", "Spinach, Paneer, Spices", 300, 12, 15, 18, "Dinner"),
        ("Moong Dal Chilla", "Moong Dal, Spices", 200, 10, 20, 5, "Breakfast"),
        ("Sewaiyan", "Vermicelli, Milk, Sugar", 250, 6, 45, 8, "Snack")
    ],
    "Uttarakhand": [
        ("Kafuli", "Spinach, Fenugreek, Spices", 150, 4, 20, 5, "Side"),
        ("Aloo Ke Gutke", "Potatoes, Spices, Oil", 200, 4, 30, 5, "Side"),
        ("Bal Mithai", "Milk Solids, Sugar, Chocolate", 500, 8, 60, 20, "Snack"),
        ("Chainsoo", "Urad Dal, Spices", 200, 8, 25, 5, "Side"),
        ("Kumaoni Raita", "Cucumber, Yogurt, Spices", 100, 3, 15, 3, "Side"),
        ("Jhangora Ki Kheer", "Millet, Milk, Sugar", 400, 6, 60, 12, "Snack"),
        ("Bhatwani", "Black Soybean, Spices", 200, 8, 25, 5, "Side"),
        ("Gahat Ki Dal", "Horse Gram, Spices", 150, 6, 20, 3, "Side"),
        ("Mandua Ki Roti", "Finger Millet, Spices", 200, 5, 35, 5, "Breakfast"),
        ("Pahadi Chicken", "Chicken, Spices, Yogurt", 350, 25, 10, 20, "Dinner"),
        ("Arsa", "Rice Flour, Jaggery, Oil", 300, 4, 45, 8, "Snack"),
        ("Singodi", "Coconut, Khoya, Malu Leaves", 250, 5, 30, 10, "Snack"),
        ("Til Ke Ladoo", "Sesame Seeds, Jaggery, Ghee", 350, 6, 40, 15, "Snack"),
        ("Urad Dal Pakora", "Urad Dal, Spices, Oil", 250, 7, 20, 12, "Snack"),
        ("Jhangora Pulao", "Millet, Vegetables, Spices", 300, 6, 45, 8, "Lunch"),
        ("Ghee Roti", "Wheat Flour, Ghee", 200, 4, 30, 10, "Breakfast"),
        ("Rus", "Pulses, Spices, Ghee", 250, 10, 20, 8, "Side"),
        ("Thhatwani", "Green Lentils, Spices", 200, 8, 25, 5, "Side"),
        ("Bhatt Ki Churkani", "Black Soybeans, Spices", 200, 8, 20, 6, "Side"),
        ("Pindalu", "Yam, Spices, Oil", 200, 5, 30, 7, "Side"),
        ("Kandali Saag", "Stinging Nettle Leaves, Spices", 150, 4, 15, 4, "Side"),
        ("Badi", "Lentil Dumplings, Spices", 250, 8, 30, 6, "Side"),
        ("Dubuk", "Pulses, Turmeric, Spices", 200, 7, 20, 5, "Side"),
        ("Aloo Jhol", "Potatoes, Spices, Tomatoes", 200, 4, 25, 6, "Side"),
        ("Lapsi", "Broken Wheat, Jaggery, Ghee", 350, 6, 50, 12, "Breakfast"),
        ("Kumaoni Thechwani", "Radish, Potatoes, Spices", 150, 4, 20, 5, "Side"),
        ("Phanu", "Mixed Pulses, Spices", 300, 10, 25, 8, "Side"),
        ("Bhaang Ki Chutney", "Hemp Seeds, Lemon, Garlic", 100, 3, 10, 5, "Side"),
        ("Churkani", "Bhatt Dal, Mustard Oil, Spices", 200, 8, 20, 6, "Side"),
        ("Gulthiya", "Wheat Dough Balls, Spices", 300, 6, 40, 10, "Lunch")
    ],
    "West Bengal": [
        ("Rasgulla", "Cheese, Sugar Syrup", 400, 8, 60, 12, "Snack"),
        ("Macher Jhol", "Fish, Spices, Mustard", 300, 20, 10, 15, "Dinner"),
        ("Shorshe Ilish", "Hilsa Fish, Mustard, Spices", 350, 22, 10, 20, "Dinner"),
        ("Luchi", "Wheat Flour, Oil", 200, 4, 30, 5, "Breakfast"),
        ("Aloo Posto", "Potatoes, Poppy Seeds, Spices", 200, 4, 30, 5, "Side"),
        ("Cholar Dal", "Chana Dal, Coconut, Spices", 150, 6, 20, 3, "Side"),
        ("Panta Bhat", "Fermented Rice, Spices", 200, 4, 35, 3, "Breakfast"),
        ("Chicken Bharta", "Chicken, Spices, Yogurt", 400, 25, 10, 20, "Dinner"),
        ("Sandesh", "Cheese, Sugar, Cardamom", 400, 8, 60, 12, "Snack"),
        ("Mishti Doi", "Yogurt, Sugar, Milk", 300, 6, 40, 10, "Snack"),
        ("Beguni", "Eggplant, Gram Flour, Spices", 250, 4, 30, 10, "Snack"),
        ("Mochar Ghonto", "Banana Flower, Potatoes, Spices", 200, 4, 25, 5, "Side"),
        ("Chingri Malai Curry", "Prawns, Coconut Milk, Spices", 400, 20, 15, 20, "Dinner"),
        ("Paturi", "Fish, Mustard Paste, Banana Leaf", 350, 22, 10, 18, "Dinner"),
        ("Shukto", "Mixed Vegetables, Bitter Gourd, Spices", 200, 4, 30, 5, "Side"),
        ("Kosha Mangsho", "Mutton, Spices, Yogurt", 450, 30, 10, 25, "Dinner"),
        ("Peyaji", "Onions, Gram Flour, Spices", 250, 4, 35, 10, "Snack"),
        ("Ghugni", "White Peas, Onions, Spices", 200, 6, 30, 5, "Snack"),
        ("Labra", "Mixed Vegetables, Panch Phoron", 200, 4, 30, 5, "Side"),
        ("Basanti Pulao", "Rice, Ghee, Saffron, Nuts", 300, 6, 40, 10, "Lunch"),
        ("Misti Polao", "Rice, Ghee, Spices, Sugar", 300, 6, 40, 10, "Lunch"),
        ("Kacha Aamer Chutney", "Raw Mango, Sugar, Mustard Seeds", 150, 2, 30, 3, "Side"),
        ("Patishapta", "Rice Flour, Coconut, Jaggery", 300, 6, 45, 8, "Snack"),
        ("Nolen Gurer Payesh", "Rice, Date Palm Jaggery, Milk", 350, 6, 50, 12, "Snack"),
        ("Radhaballabhi", "Stuffed Wheat Flour Puri, Dal", 300, 8, 40, 10, "Breakfast"),
        ("Murighonto", "Fish Head, Rice, Spices", 350, 18, 35, 15, "Lunch"),
        ("Dhokar Dalna", "Lentil Cakes, Spices, Potatoes", 250, 10, 20, 8, "Lunch"),
        ("Chhanar Dalna", "Paneer, Tomatoes, Spices", 300, 14, 20, 10, "Dinner"),
        ("Kheer Kadam", "Milk Solids, Sugar", 450, 10, 60, 15, "Snack")
    ]
}
# Seasonal fruits and vegetables for each state
STATE_SEASONAL_PRODUCE = {
    "Andhra Pradesh": {
        "Summer": {"Fruits": ["Mango", "Watermelon", "Muskmelon"], "Vegetables": ["Cucumber", "Bottle Gourd", "Okra"]},
        "Monsoon": {"Fruits": ["Jamun", "Pear", "Plum"], "Vegetables": ["Bitter Gourd", "Ridge Gourd", "Corn"]},
        "Autumn": {"Fruits": ["Guava", "Custard Apple", "Pomegranate"], "Vegetables": ["Pumpkin", "Brinjal", "Green Beans"]},
        "Winter": {"Fruits": ["Orange", "Papaya", "Grapes"], "Vegetables": ["Carrot", "Cauliflower", "Peas"]}
    },
    "Arunachal Pradesh": {
        "Summer": {"Fruits": ["Pineapple", "Mango", "Litchi"], "Vegetables": ["Cucumber", "Bamboo Shoot", "Okra"]},
        "Monsoon": {"Fruits": ["Jackfruit", "Plum", "Peach"], "Vegetables": ["Fern Leaves", "Colocasia", "Corn"]},
        "Autumn": {"Fruits": ["Orange", "Kiwi", "Pomegranate"], "Vegetables": ["Pumpkin", "Brinjal", "Radish"]},
        "Winter": {"Fruits": ["Apple", "Banana", "Grapes"], "Vegetables": ["Cabbage", "Cauliflower", "Mustard Greens"]}
    },
    "Assam": {
        "Summer": {"Fruits": ["Mango", "Litchi", "Pineapple"], "Vegetables": ["Cucumber", "Bottle Gourd", "Okra"]},
        "Monsoon": {"Fruits": ["Jackfruit", "Jamun", "Plum"], "Vegetables": ["Bamboo Shoot", "Colocasia", "Fern Leaves"]},
        "Autumn": {"Fruits": ["Guava", "Pomegranate", "Custard Apple"], "Vegetables": ["Pumpkin", "Brinjal", "Radish"]},
        "Winter": {"Fruits": ["Orange", "Banana", "Papaya"], "Vegetables": ["Cabbage", "Cauliflower", "Peas"]}
    },
    "Bihar": {
        "Summer": {"Fruits": ["Mango", "Litchi", "Watermelon"], "Vegetables": ["Cucumber", "Bottle Gourd", "Okra"]},
        "Monsoon": {"Fruits": ["Jamun", "Plum", "Pear"], "Vegetables": ["Bitter Gourd", "Ridge Gourd", "Corn"]},
        "Autumn": {"Fruits": ["Guava", "Pomegranate", "Custard Apple"], "Vegetables": ["Pumpkin", "Brinjal", "Green Beans"]},
        "Winter": {"Fruits": ["Orange", "Banana", "Grapes"], "Vegetables": ["Carrot", "Cauliflower", "Peas"]}
    },
    "Chattisgarh": {
        "Summer": {"Fruits": ["Mango", "Watermelon", "Muskmelon"], "Vegetables": ["Cucumber", "Bottle Gourd", "Okra"]},
        "Monsoon": {"Fruits": ["Jamun", "Plum", "Jackfruit"], "Vegetables": ["Bitter Gourd", "Ridge Gourd", "Corn"]},
        "Autumn": {"Fruits": ["Guava", "Pomegranate", "Custard Apple"], "Vegetables": ["Pumpkin", "Brinjal", "Green Beans"]},
        "Winter": {"Fruits": ["Orange", "Papaya", "Grapes"], "Vegetables": ["Carrot", "Cauliflower", "Peas"]}
    },
    "Goa": {
        "Summer": {"Fruits": ["Mango", "Jackfruit", "Cashew Apple"], "Vegetables": ["Cucumber", "Bottle Gourd", "Okra"]},
        "Monsoon": {"Fruits": ["Jamun", "Plum", "Pineapple"], "Vegetables": ["Colocasia", "Yam", "Corn"]},
        "Autumn": {"Fruits": ["Guava", "Custard Apple", "Pomegranate"], "Vegetables": ["Pumpkin", "Brinjal", "Green Beans"]},
        "Winter": {"Fruits": ["Banana", "Papaya", "Orange"], "Vegetables": ["Cabbage", "Cauliflower", "Peas"]}
    },
    "Gujarat": {
        "Summer": {"Fruits": ["Mango", "Watermelon", "Muskmelon"], "Vegetables": ["Cucumber", "Bottle Gourd", "Okra"]},
        "Monsoon": {"Fruits": ["Jamun", "Plum", "Pear"], "Vegetables": ["Bitter Gourd", "Ridge Gourd", "Corn"]},
        "Autumn": {"Fruits": ["Guava", "Pomegranate", "Custard Apple"], "Vegetables": ["Pumpkin", "Brinjal", "Green Beans"]},
        "Winter": {"Fruits": ["Orange", "Chikoo", "Grapes"], "Vegetables": ["Carrot", "Cauliflower", "Peas"]}
    },
    "Haryana": {
        "Summer": {"Fruits": ["Mango", "Watermelon", "Muskmelon"], "Vegetables": ["Cucumber", "Bottle Gourd", "Okra"]},
        "Monsoon": {"Fruits": ["Jamun", "Plum", "Pear"], "Vegetables": ["Bitter Gourd", "Ridge Gourd", "Corn"]},
        "Autumn": {"Fruits": ["Guava", "Pomegranate", "Custard Apple"], "Vegetables": ["Pumpkin", "Brinjal", "Green Beans"]},
        "Winter": {"Fruits": ["Orange", "Kinnow", "Grapes"], "Vegetables": ["Carrot", "Cauliflower", "Peas"]}
    },
    "Himachal Pradesh": {
        "Summer": {"Fruits": ["Mango", "Litchi", "Peach"], "Vegetables": ["Cucumber", "Bottle Gourd", "Okra"]},
        "Monsoon": {"Fruits": ["Plum", "Pear", "Apple"], "Vegetables": ["Bitter Gourd", "Ridge Gourd", "Corn"]},
        "Autumn": {"Fruits": ["Apple", "Pomegranate", "Kiwi"], "Vegetables": ["Pumpkin", "Brinjal", "Radish"]},
        "Winter": {"Fruits": ["Orange", "Kinnow", "Grapes"], "Vegetables": ["Cabbage", "Cauliflower", "Peas"]}
    },
    "Jharkhand": {
        "Summer": {"Fruits": ["Mango", "Litchi", "Watermelon"], "Vegetables": ["Cucumber", "Bottle Gourd", "Okra"]},
        "Monsoon": {"Fruits": ["Jamun", "Plum", "Jackfruit"], "Vegetables": ["Bitter Gourd", "Ridge Gourd", "Corn"]},
        "Autumn": {"Fruits": ["Guava", "Pomegranate", "Custard Apple"], "Vegetables": ["Pumpkin", "Brinjal", "Green Beans"]},
        "Winter": {"Fruits": ["Orange", "Papaya", "Grapes"], "Vegetables": ["Carrot", "Cauliflower", "Peas"]}
    },
    "Karnataka": {
        "Summer": {"Fruits": ["Mango", "Jackfruit", "Watermelon"], "Vegetables": ["Cucumber", "Bottle Gourd", "Okra"]},
        "Monsoon": {"Fruits": ["Jamun", "Plum", "Pineapple"], "Vegetables": ["Bitter Gourd", "Ridge Gourd", "Corn"]},
        "Autumn": {"Fruits": ["Guava", "Custard Apple", "Pomegranate"], "Vegetables": ["Pumpkin", "Brinjal", "Green Beans"]},
        "Winter": {"Fruits": ["Orange", "Chikoo", "Grapes"], "Vegetables": ["Carrot", "Cauliflower", "Peas"]}
    },
    "Kerala": {
        "Summer": {"Fruits": ["Mango", "Jackfruit", "Pineapple"], "Vegetables": ["Cucumber", "Bottle Gourd", "Okra"]},
        "Monsoon": {"Fruits": ["Banana", "Papaya", "Rambutan"], "Vegetables": ["Colocasia", "Yam", "Corn"]},
        "Autumn": {"Fruits": ["Guava", "Custard Apple", "Pomegranate"], "Vegetables": ["Pumpkin", "Brinjal", "Green Beans"]},
        "Winter": {"Fruits": ["Banana", "Orange", "Grapes"], "Vegetables": ["Cabbage", "Cauliflower", "Peas"]}
    },
    "Madya Pradesh": {
        "Summer": {"Fruits": ["Mango", "Watermelon", "Muskmelon"], "Vegetables": ["Cucumber", "Bottle Gourd", "Okra"]},
        "Monsoon": {"Fruits": ["Jamun", "Plum", "Pear"], "Vegetables": ["Bitter Gourd", "Ridge Gourd", "Corn"]},
        "Autumn": {"Fruits": ["Guava", "Pomegranate", "Custard Apple"], "Vegetables": ["Pumpkin", "Brinjal", "Green Beans"]},
        "Winter": {"Fruits": ["Orange", "Chikoo", "Grapes"], "Vegetables": ["Carrot", "Cauliflower", "Peas"]}
    },
    "Maharashta": {
        "Summer": {"Fruits": ["Mango", "Watermelon", "Muskmelon"], "Vegetables": ["Cucumber", "Bottle Gourd", "Okra"]},
        "Monsoon": {"Fruits": ["Jamun", "Plum", "Pear"], "Vegetables": ["Bitter Gourd", "Ridge Gourd", "Corn"]},
        "Autumn": {"Fruits": ["Guava", "Pomegranate", "Custard Apple"], "Vegetables": ["Pumpkin", "Brinjal", "Green Beans"]},
        "Winter": {"Fruits": ["Orange", "Chikoo", "Grapes"], "Vegetables": ["Carrot", "Cauliflower", "Peas"]}
    },
    "Manipur": {
        "Summer": {"Fruits": ["Mango", "Pineapple", "Litchi"], "Vegetables": ["Cucumber", "Bamboo Shoot", "Okra"]},
        "Monsoon": {"Fruits": ["Jackfruit", "Plum", "Peach"], "Vegetables": ["Fern Leaves", "Colocasia", "Corn"]},
        "Autumn": {"Fruits": ["Orange", "Pomegranate", "Guava"], "Vegetables": ["Pumpkin", "Brinjal", "Radish"]},
        "Winter": {"Fruits": ["Banana", "Orange", "Grapes"], "Vegetables": ["Cabbage", "Cauliflower", "Mustard Greens"]}
    },
    "Meghalaya": {
        "Summer": {"Fruits": ["Pineapple", "Mango", "Litchi"], "Vegetables": ["Cucumber", "Bamboo Shoot", "Okra"]},
        "Monsoon": {"Fruits": ["Jackfruit", "Plum", "Peach"], "Vegetables": ["Fern Leaves", "Colocasia", "Corn"]},
        "Autumn": {"Fruits": ["Orange", "Pomegranate", "Guava"], "Vegetables": ["Pumpkin", "Brinjal", "Radish"]},
        "Winter": {"Fruits": ["Banana", "Orange", "Grapes"], "Vegetables": ["Cabbage", "Cauliflower", "Mustard Greens"]}
    },
    "Mizoram": {
        "Summer": {"Fruits": ["Pineapple", "Mango", "Litchi"], "Vegetables": ["Cucumber", "Bamboo Shoot", "Okra"]},
        "Monsoon": {"Fruits": ["Jackfruit", "Plum", "Peach"], "Vegetables": ["Fern Leaves", "Colocasia", "Corn"]},
        "Autumn": {"Fruits": ["Orange", "Pomegranate", "Guava"], "Vegetables": ["Pumpkin", "Brinjal", "Radish"]},
        "Winter": {"Fruits": ["Banana", "Orange", "Grapes"], "Vegetables": ["Cabbage", "Cauliflower", "Mustard Greens"]}
    },
    "Nagaland": {
        "Summer": {"Fruits": ["Pineapple", "Mango", "Litchi"], "Vegetables": ["Cucumber", "Bamboo Shoot", "Okra"]},
        "Monsoon": {"Fruits": ["Jackfruit", "Plum", "Peach"], "Vegetables": ["Fern Leaves", "Colocasia", "Corn"]},
        "Autumn": {"Fruits": ["Orange", "Pomegranate", "Guava"], "Vegetables": ["Pumpkin", "Brinjal", "Radish"]},
        "Winter": {"Fruits": ["Banana", "Orange", "Grapes"], "Vegetables": ["Cabbage", "Cauliflower", "Mustard Greens"]}
    },
    "Odisha": {
        "Summer": {"Fruits": ["Mango", "Watermelon", "Jackfruit"], "Vegetables": ["Cucumber", "Bottle Gourd", "Okra"]},
        "Monsoon": {"Fruits": ["Jamun", "Plum", "Pineapple"], "Vegetables": ["Bitter Gourd", "Ridge Gourd", "Corn"]},
        "Autumn": {"Fruits": ["Guava", "Pomegranate", "Custard Apple"], "Vegetables": ["Pumpkin", "Brinjal", "Green Beans"]},
        "Winter": {"Fruits": ["Orange", "Papaya", "Grapes"], "Vegetables": ["Carrot", "Cauliflower", "Peas"]}
    },
    "Punjab": {
        "Summer": {"Fruits": ["Mango", "Watermelon", "Muskmelon"], "Vegetables": ["Cucumber", "Bottle Gourd", "Okra"]},
        "Monsoon": {"Fruits": ["Jamun", "Plum", "Pear"], "Vegetables": ["Bitter Gourd", "Ridge Gourd", "Corn"]},
        "Autumn": {"Fruits": ["Guava", "Pomegranate", "Custard Apple"], "Vegetables": ["Pumpkin", "Brinjal", "Green Beans"]},
        "Winter": {"Fruits": ["Orange", "Kinnow", "Grapes"], "Vegetables": ["Carrot", "Cauliflower", "Peas", "Mustard Greens"]}
    },
    "Rajasthan": {
        "Summer": {"Fruits": ["Mango", "Watermelon", "Muskmelon"], "Vegetables": ["Cucumber", "Bottle Gourd", "Okra"]},
        "Monsoon": {"Fruits": ["Jamun", "Plum", "Pear"], "Vegetables": ["Bitter Gourd", "Ridge Gourd", "Corn"]},
        "Autumn": {"Fruits": ["Guava", "Pomegranate", "Custard Apple"], "Vegetables": ["Pumpkin", "Brinjal", "Green Beans"]},
        "Winter": {"Fruits": ["Orange", "Kinnow", "Grapes"], "Vegetables": ["Carrot", "Cauliflower", "Peas"]}
    },
    "Sikkim": {
        "Summer": {"Fruits": ["Mango", "Litchi", "Peach"], "Vegetables": ["Cucumber", "Bottle Gourd", "Okra"]},
        "Monsoon": {"Fruits": ["Plum", "Pear", "Apple"], "Vegetables": ["Bitter Gourd", "Ridge Gourd", "Corn"]},
        "Autumn": {"Fruits": ["Orange", "Pomegranate", "Kiwi"], "Vegetables": ["Pumpkin", "Brinjal", "Radish"]},
        "Winter": {"Fruits": ["Orange", "Apple", "Grapes"], "Vegetables": ["Cabbage", "Cauliflower", "Peas"]}
    },
    "Tamil Nadu": {
        "Summer": {"Fruits": ["Mango", "Jackfruit", "Watermelon"], "Vegetables": ["Cucumber", "Bottle Gourd", "Okra"]},
        "Monsoon": {"Fruits": ["Banana", "Papaya", "Guava"], "Vegetables": ["Colocasia", "Yam", "Corn"]},
        "Autumn": {"Fruits": ["Guava", "Custard Apple", "Pomegranate"], "Vegetables": ["Pumpkin", "Brinjal", "Green Beans"]},
        "Winter": {"Fruits": ["Banana", "Orange", "Grapes"], "Vegetables": ["Carrot", "Cauliflower", "Peas"]}
    },
    "Telangana": {
        "Summer": {"Fruits": ["Mango", "Watermelon", "Muskmelon"], "Vegetables": ["Cucumber", "Bottle Gourd", "Okra"]},
        "Monsoon": {"Fruits": ["Jamun", "Plum", "Pear"], "Vegetables": ["Bitter Gourd", "Ridge Gourd", "Corn"]},
        "Autumn": {"Fruits": ["Guava", "Pomegranate", "Custard Apple"], "Vegetables": ["Pumpkin", "Brinjal", "Green Beans"]},
        "Winter": {"Fruits": ["Orange", "Papaya", "Grapes"], "Vegetables": ["Carrot", "Cauliflower", "Peas"]}
    },
    "Tripura": {
        "Summer": {"Fruits": ["Mango", "Pineapple", "Litchi"], "Vegetables": ["Cucumber", "Bamboo Shoot", "Okra"]},
        "Monsoon": {"Fruits": ["Jackfruit", "Plum", "Peach"], "Vegetables": ["Fern Leaves", "Colocasia", "Corn"]},
        "Autumn": {"Fruits": ["Orange", "Pomegranate", "Guava"], "Vegetables": ["Pumpkin", "Brinjal", "Radish"]},
        "Winter": {"Fruits": ["Banana", "Orange", "Grapes"], "Vegetables": ["Cabbage", "Cauliflower", "Mustard Greens"]}
    },
    "Uttar Pradesh": {
        "Summer": {"Fruits": ["Mango", "Litchi", "Watermelon"], "Vegetables": ["Cucumber", "Bottle Gourd", "Okra"]},
        "Monsoon": {"Fruits": ["Jamun", "Plum", "Pear"], "Vegetables": ["Bitter Gourd", "Ridge Gourd", "Corn"]},
        "Autumn": {"Fruits": ["Guava", "Pomegranate", "Custard Apple"], "Vegetables": ["Pumpkin", "Brinjal", "Green Beans"]},
        "Winter": {"Fruits": ["Orange", "Kinnow", "Grapes"], "Vegetables": ["Carrot", "Cauliflower", "Peas"]}
    },
    "Uttarakhand": {
        "Summer": {"Fruits": ["Mango", "Litchi", "Peach"], "Vegetables": ["Cucumber", "Bottle Gourd", "Okra"]},
        "Monsoon": {"Fruits": ["Plum", "Pear", "Apple"], "Vegetables": ["Bitter Gourd", "Ridge Gourd", "Corn"]},
        "Autumn": {"Fruits": ["Apple", "Pomegranate", "Kiwi"], "Vegetables": ["Pumpkin", "Brinjal", "Radish"]},
        "Winter": {"Fruits": ["Orange", "Apple", "Grapes"], "Vegetables": ["Cabbage", "Cauliflower", "Peas"]}
    },
    "West Bengal": {
        "Summer": {"Fruits": ["Mango", "Litchi", "Watermelon"], "Vegetables": ["Cucumber", "Bottle Gourd", "Okra"]},
        "Monsoon": {"Fruits": ["Jamun", "Plum", "Pineapple"], "Vegetables": ["Bitter Gourd", "Ridge Gourd", "Corn"]},
        "Autumn": {"Fruits": ["Guava", "Pomegranate", "Custard Apple"], "Vegetables": ["Pumpkin", "Brinjal", "Green Beans"]},
        "Winter": {"Fruits": ["Orange", "Papaya", "Grapes"], "Vegetables": ["Carrot", "Cauliflower", "Peas"]}
    }
}

# List of states for easy access
STATES = list(STATE_FOODS.keys())
